// Code generated by ent, DO NOT EDIT.

package apitoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/felipekafuri/bandeira/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLTE(FieldID, id))
}

// Secret applies equality check predicate on the "secret" field. It's identical to SecretEQ.
func Secret(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldSecret, v))
}

// PlainToken applies equality check predicate on the "plain_token" field. It's identical to PlainTokenEQ.
func PlainToken(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldPlainToken, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldName, v))
}

// Environment applies equality check predicate on the "environment" field. It's identical to EnvironmentEQ.
func Environment(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldEnvironment, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldProjectID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// SecretEQ applies the EQ predicate on the "secret" field.
func SecretEQ(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldSecret, v))
}

// SecretNEQ applies the NEQ predicate on the "secret" field.
func SecretNEQ(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldSecret, v))
}

// SecretIn applies the In predicate on the "secret" field.
func SecretIn(vs ...string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldSecret, vs...))
}

// SecretNotIn applies the NotIn predicate on the "secret" field.
func SecretNotIn(vs ...string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldSecret, vs...))
}

// SecretGT applies the GT predicate on the "secret" field.
func SecretGT(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGT(FieldSecret, v))
}

// SecretGTE applies the GTE predicate on the "secret" field.
func SecretGTE(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGTE(FieldSecret, v))
}

// SecretLT applies the LT predicate on the "secret" field.
func SecretLT(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLT(FieldSecret, v))
}

// SecretLTE applies the LTE predicate on the "secret" field.
func SecretLTE(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLTE(FieldSecret, v))
}

// SecretContains applies the Contains predicate on the "secret" field.
func SecretContains(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldContains(FieldSecret, v))
}

// SecretHasPrefix applies the HasPrefix predicate on the "secret" field.
func SecretHasPrefix(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldHasPrefix(FieldSecret, v))
}

// SecretHasSuffix applies the HasSuffix predicate on the "secret" field.
func SecretHasSuffix(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldHasSuffix(FieldSecret, v))
}

// SecretEqualFold applies the EqualFold predicate on the "secret" field.
func SecretEqualFold(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEqualFold(FieldSecret, v))
}

// SecretContainsFold applies the ContainsFold predicate on the "secret" field.
func SecretContainsFold(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldContainsFold(FieldSecret, v))
}

// PlainTokenEQ applies the EQ predicate on the "plain_token" field.
func PlainTokenEQ(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldPlainToken, v))
}

// PlainTokenNEQ applies the NEQ predicate on the "plain_token" field.
func PlainTokenNEQ(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldPlainToken, v))
}

// PlainTokenIn applies the In predicate on the "plain_token" field.
func PlainTokenIn(vs ...string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldPlainToken, vs...))
}

// PlainTokenNotIn applies the NotIn predicate on the "plain_token" field.
func PlainTokenNotIn(vs ...string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldPlainToken, vs...))
}

// PlainTokenGT applies the GT predicate on the "plain_token" field.
func PlainTokenGT(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGT(FieldPlainToken, v))
}

// PlainTokenGTE applies the GTE predicate on the "plain_token" field.
func PlainTokenGTE(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGTE(FieldPlainToken, v))
}

// PlainTokenLT applies the LT predicate on the "plain_token" field.
func PlainTokenLT(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLT(FieldPlainToken, v))
}

// PlainTokenLTE applies the LTE predicate on the "plain_token" field.
func PlainTokenLTE(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLTE(FieldPlainToken, v))
}

// PlainTokenContains applies the Contains predicate on the "plain_token" field.
func PlainTokenContains(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldContains(FieldPlainToken, v))
}

// PlainTokenHasPrefix applies the HasPrefix predicate on the "plain_token" field.
func PlainTokenHasPrefix(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldHasPrefix(FieldPlainToken, v))
}

// PlainTokenHasSuffix applies the HasSuffix predicate on the "plain_token" field.
func PlainTokenHasSuffix(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldHasSuffix(FieldPlainToken, v))
}

// PlainTokenEqualFold applies the EqualFold predicate on the "plain_token" field.
func PlainTokenEqualFold(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEqualFold(FieldPlainToken, v))
}

// PlainTokenContainsFold applies the ContainsFold predicate on the "plain_token" field.
func PlainTokenContainsFold(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldContainsFold(FieldPlainToken, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldContainsFold(FieldName, v))
}

// TokenTypeEQ applies the EQ predicate on the "token_type" field.
func TokenTypeEQ(v TokenType) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldTokenType, v))
}

// TokenTypeNEQ applies the NEQ predicate on the "token_type" field.
func TokenTypeNEQ(v TokenType) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldTokenType, v))
}

// TokenTypeIn applies the In predicate on the "token_type" field.
func TokenTypeIn(vs ...TokenType) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldTokenType, vs...))
}

// TokenTypeNotIn applies the NotIn predicate on the "token_type" field.
func TokenTypeNotIn(vs ...TokenType) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldTokenType, vs...))
}

// EnvironmentEQ applies the EQ predicate on the "environment" field.
func EnvironmentEQ(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldEnvironment, v))
}

// EnvironmentNEQ applies the NEQ predicate on the "environment" field.
func EnvironmentNEQ(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldEnvironment, v))
}

// EnvironmentIn applies the In predicate on the "environment" field.
func EnvironmentIn(vs ...string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldEnvironment, vs...))
}

// EnvironmentNotIn applies the NotIn predicate on the "environment" field.
func EnvironmentNotIn(vs ...string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldEnvironment, vs...))
}

// EnvironmentGT applies the GT predicate on the "environment" field.
func EnvironmentGT(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGT(FieldEnvironment, v))
}

// EnvironmentGTE applies the GTE predicate on the "environment" field.
func EnvironmentGTE(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGTE(FieldEnvironment, v))
}

// EnvironmentLT applies the LT predicate on the "environment" field.
func EnvironmentLT(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLT(FieldEnvironment, v))
}

// EnvironmentLTE applies the LTE predicate on the "environment" field.
func EnvironmentLTE(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLTE(FieldEnvironment, v))
}

// EnvironmentContains applies the Contains predicate on the "environment" field.
func EnvironmentContains(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldContains(FieldEnvironment, v))
}

// EnvironmentHasPrefix applies the HasPrefix predicate on the "environment" field.
func EnvironmentHasPrefix(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldHasPrefix(FieldEnvironment, v))
}

// EnvironmentHasSuffix applies the HasSuffix predicate on the "environment" field.
func EnvironmentHasSuffix(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldHasSuffix(FieldEnvironment, v))
}

// EnvironmentIsNil applies the IsNil predicate on the "environment" field.
func EnvironmentIsNil() predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIsNull(FieldEnvironment))
}

// EnvironmentNotNil applies the NotNil predicate on the "environment" field.
func EnvironmentNotNil() predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotNull(FieldEnvironment))
}

// EnvironmentEqualFold applies the EqualFold predicate on the "environment" field.
func EnvironmentEqualFold(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEqualFold(FieldEnvironment, v))
}

// EnvironmentContainsFold applies the ContainsFold predicate on the "environment" field.
func EnvironmentContainsFold(v string) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldContainsFold(FieldEnvironment, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldProjectID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ApiToken {
	return predicate.ApiToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.ApiToken {
	return predicate.ApiToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.ApiToken {
	return predicate.ApiToken(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApiToken) predicate.ApiToken {
	return predicate.ApiToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApiToken) predicate.ApiToken {
	return predicate.ApiToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApiToken) predicate.ApiToken {
	return predicate.ApiToken(sql.NotPredicates(p))
}
