// Code generated by ent, DO NOT EDIT.
package admin

import (
	"time"

	"github.com/felipekafuri/bandeira/ent/apitoken"
	"github.com/felipekafuri/bandeira/ent/constraint"
	"github.com/felipekafuri/bandeira/ent/environment"
	"github.com/felipekafuri/bandeira/ent/flag"
	"github.com/felipekafuri/bandeira/ent/user"
)

type ApiToken struct {
	Secret      *string            `form:"secret"`
	PlainToken  *string            `form:"plain_token"`
	Name        string             `form:"name"`
	TokenType   apitoken.TokenType `form:"token_type"`
	Environment *string            `form:"environment"`
	ProjectID   int                `form:"project_id"`
	CreatedBy   *int               `form:"created_by"`
	CreatedAt   *time.Time         `form:"created_at"`
	UpdatedAt   *time.Time         `form:"updated_at"`
}

type Constraint struct {
	ContextName     string              `form:"context_name"`
	Operator        constraint.Operator `form:"operator"`
	Values          []string            `form:"values"`
	Inverted        bool                `form:"inverted"`
	CaseInsensitive bool                `form:"case_insensitive"`
	StrategyID      int                 `form:"strategy_id"`
	CreatedAt       *time.Time          `form:"created_at"`
	UpdatedAt       *time.Time          `form:"updated_at"`
}

type Environment struct {
	Name      string           `form:"name"`
	Type      environment.Type `form:"type"`
	SortOrder *int             `form:"sort_order"`
	ProjectID int              `form:"project_id"`
	CreatedAt *time.Time       `form:"created_at"`
	UpdatedAt *time.Time       `form:"updated_at"`
}

type Flag struct {
	Name        string        `form:"name"`
	Description *string       `form:"description"`
	FlagType    flag.FlagType `form:"flag_type"`
	ProjectID   int           `form:"project_id"`
	CreatedAt   *time.Time    `form:"created_at"`
	UpdatedAt   *time.Time    `form:"updated_at"`
}

type FlagEnvironment struct {
	Enabled       bool       `form:"enabled"`
	FlagID        int        `form:"flag_id"`
	EnvironmentID int        `form:"environment_id"`
	CreatedAt     *time.Time `form:"created_at"`
	UpdatedAt     *time.Time `form:"updated_at"`
}

type Project struct {
	Name        string     `form:"name"`
	Description *string    `form:"description"`
	CreatedAt   *time.Time `form:"created_at"`
	UpdatedAt   *time.Time `form:"updated_at"`
}

type Strategy struct {
	Name              string                  `form:"name"`
	Parameters        *map[string]interface{} `form:"parameters"`
	SortOrder         *int                    `form:"sort_order"`
	FlagEnvironmentID int                     `form:"flag_environment_id"`
	CreatedAt         *time.Time              `form:"created_at"`
	UpdatedAt         *time.Time              `form:"updated_at"`
}

type User struct {
	Email     string     `form:"email"`
	Password  *string    `form:"password"`
	Name      string     `form:"name"`
	Role      *user.Role `form:"role"`
	CreatedAt *time.Time `form:"created_at"`
	UpdatedAt *time.Time `form:"updated_at"`
}

type EntityList struct {
	Columns     []string
	Entities    []EntityValues
	Page        int
	HasNextPage bool
}

type EntityValues struct {
	ID     int
	Values []string
}

type HandlerConfig struct {
	ItemsPerPage int
	PageQueryKey string
	TimeFormat   string
}

func GetEntityTypeNames() []string {
	return []string{
		"ApiToken",
		"Constraint",
		"Environment",
		"Flag",
		"FlagEnvironment",
		"Project",
		"Strategy",
		"User",
	}
}
