// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APITokensColumns holds the columns for the "api_tokens" table.
	APITokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "secret", Type: field.TypeString},
		{Name: "plain_token", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString},
		{Name: "token_type", Type: field.TypeEnum, Enums: []string{"client", "admin"}},
		{Name: "environment", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
	}
	// APITokensTable holds the schema information for the "api_tokens" table.
	APITokensTable = &schema.Table{
		Name:       "api_tokens",
		Columns:    APITokensColumns,
		PrimaryKey: []*schema.Column{APITokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_tokens_projects_api_tokens",
				Columns:    []*schema.Column{APITokensColumns[8]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_tokens_users_api_tokens",
				Columns:    []*schema.Column{APITokensColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ConstraintsColumns holds the columns for the "constraints" table.
	ConstraintsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "context_name", Type: field.TypeString},
		{Name: "operator", Type: field.TypeEnum, Enums: []string{"IN", "NOT_IN", "STR_CONTAINS", "STR_STARTS_WITH", "STR_ENDS_WITH", "NUM_EQ", "NUM_GT", "NUM_GTE", "NUM_LT", "NUM_LTE", "DATE_AFTER", "DATE_BEFORE"}},
		{Name: "values", Type: field.TypeJSON},
		{Name: "inverted", Type: field.TypeBool, Default: false},
		{Name: "case_insensitive", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "strategy_id", Type: field.TypeInt},
	}
	// ConstraintsTable holds the schema information for the "constraints" table.
	ConstraintsTable = &schema.Table{
		Name:       "constraints",
		Columns:    ConstraintsColumns,
		PrimaryKey: []*schema.Column{ConstraintsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "constraints_strategies_constraints",
				Columns:    []*schema.Column{ConstraintsColumns[8]},
				RefColumns: []*schema.Column{StrategiesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// EnvironmentsColumns holds the columns for the "environments" table.
	EnvironmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"development", "staging", "production"}},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_id", Type: field.TypeInt},
	}
	// EnvironmentsTable holds the schema information for the "environments" table.
	EnvironmentsTable = &schema.Table{
		Name:       "environments",
		Columns:    EnvironmentsColumns,
		PrimaryKey: []*schema.Column{EnvironmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "environments_projects_environments",
				Columns:    []*schema.Column{EnvironmentsColumns[6]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "environment_name_project_id",
				Unique:  true,
				Columns: []*schema.Column{EnvironmentsColumns[1], EnvironmentsColumns[6]},
			},
		},
	}
	// FlagsColumns holds the columns for the "flags" table.
	FlagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "flag_type", Type: field.TypeEnum, Enums: []string{"release", "experiment", "operational", "kill_switch"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_id", Type: field.TypeInt},
	}
	// FlagsTable holds the schema information for the "flags" table.
	FlagsTable = &schema.Table{
		Name:       "flags",
		Columns:    FlagsColumns,
		PrimaryKey: []*schema.Column{FlagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "flags_projects_flags",
				Columns:    []*schema.Column{FlagsColumns[6]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "flag_name_project_id",
				Unique:  true,
				Columns: []*schema.Column{FlagsColumns[1], FlagsColumns[6]},
			},
		},
	}
	// FlagEnvironmentsColumns holds the columns for the "flag_environments" table.
	FlagEnvironmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "environment_id", Type: field.TypeInt},
		{Name: "flag_id", Type: field.TypeInt},
	}
	// FlagEnvironmentsTable holds the schema information for the "flag_environments" table.
	FlagEnvironmentsTable = &schema.Table{
		Name:       "flag_environments",
		Columns:    FlagEnvironmentsColumns,
		PrimaryKey: []*schema.Column{FlagEnvironmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "flag_environments_environments_flag_environments",
				Columns:    []*schema.Column{FlagEnvironmentsColumns[4]},
				RefColumns: []*schema.Column{EnvironmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "flag_environments_flags_flag_environments",
				Columns:    []*schema.Column{FlagEnvironmentsColumns[5]},
				RefColumns: []*schema.Column{FlagsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "flagenvironment_flag_id_environment_id",
				Unique:  true,
				Columns: []*schema.Column{FlagEnvironmentsColumns[5], FlagEnvironmentsColumns[4]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// StrategiesColumns holds the columns for the "strategies" table.
	StrategiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "parameters", Type: field.TypeJSON, Nullable: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "flag_environment_id", Type: field.TypeInt},
	}
	// StrategiesTable holds the schema information for the "strategies" table.
	StrategiesTable = &schema.Table{
		Name:       "strategies",
		Columns:    StrategiesColumns,
		PrimaryKey: []*schema.Column{StrategiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "strategies_flag_environments_strategies",
				Columns:    []*schema.Column{StrategiesColumns[6]},
				RefColumns: []*schema.Column{FlagEnvironmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "editor", "viewer"}, Default: "viewer"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APITokensTable,
		ConstraintsTable,
		EnvironmentsTable,
		FlagsTable,
		FlagEnvironmentsTable,
		ProjectsTable,
		StrategiesTable,
		UsersTable,
	}
)

func init() {
	APITokensTable.ForeignKeys[0].RefTable = ProjectsTable
	APITokensTable.ForeignKeys[1].RefTable = UsersTable
	ConstraintsTable.ForeignKeys[0].RefTable = StrategiesTable
	EnvironmentsTable.ForeignKeys[0].RefTable = ProjectsTable
	FlagsTable.ForeignKeys[0].RefTable = ProjectsTable
	FlagEnvironmentsTable.ForeignKeys[0].RefTable = EnvironmentsTable
	FlagEnvironmentsTable.ForeignKeys[1].RefTable = FlagsTable
	StrategiesTable.ForeignKeys[0].RefTable = FlagEnvironmentsTable
}
