// Code generated by ent, DO NOT EDIT.

package flagenvironment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the flagenvironment type in the database.
	Label = "flag_environment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldFlagID holds the string denoting the flag_id field in the database.
	FieldFlagID = "flag_id"
	// FieldEnvironmentID holds the string denoting the environment_id field in the database.
	FieldEnvironmentID = "environment_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeFlag holds the string denoting the flag edge name in mutations.
	EdgeFlag = "flag"
	// EdgeEnvironment holds the string denoting the environment edge name in mutations.
	EdgeEnvironment = "environment"
	// EdgeStrategies holds the string denoting the strategies edge name in mutations.
	EdgeStrategies = "strategies"
	// Table holds the table name of the flagenvironment in the database.
	Table = "flag_environments"
	// FlagTable is the table that holds the flag relation/edge.
	FlagTable = "flag_environments"
	// FlagInverseTable is the table name for the Flag entity.
	// It exists in this package in order to avoid circular dependency with the "flag" package.
	FlagInverseTable = "flags"
	// FlagColumn is the table column denoting the flag relation/edge.
	FlagColumn = "flag_id"
	// EnvironmentTable is the table that holds the environment relation/edge.
	EnvironmentTable = "flag_environments"
	// EnvironmentInverseTable is the table name for the Environment entity.
	// It exists in this package in order to avoid circular dependency with the "environment" package.
	EnvironmentInverseTable = "environments"
	// EnvironmentColumn is the table column denoting the environment relation/edge.
	EnvironmentColumn = "environment_id"
	// StrategiesTable is the table that holds the strategies relation/edge.
	StrategiesTable = "strategies"
	// StrategiesInverseTable is the table name for the Strategy entity.
	// It exists in this package in order to avoid circular dependency with the "strategy" package.
	StrategiesInverseTable = "strategies"
	// StrategiesColumn is the table column denoting the strategies relation/edge.
	StrategiesColumn = "flag_environment_id"
)

// Columns holds all SQL columns for flagenvironment fields.
var Columns = []string{
	FieldID,
	FieldEnabled,
	FieldFlagID,
	FieldEnvironmentID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the FlagEnvironment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByFlagID orders the results by the flag_id field.
func ByFlagID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlagID, opts...).ToFunc()
}

// ByEnvironmentID orders the results by the environment_id field.
func ByEnvironmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByFlagField orders the results by flag field.
func ByFlagField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlagStep(), sql.OrderByField(field, opts...))
	}
}

// ByEnvironmentField orders the results by environment field.
func ByEnvironmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnvironmentStep(), sql.OrderByField(field, opts...))
	}
}

// ByStrategiesCount orders the results by strategies count.
func ByStrategiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStrategiesStep(), opts...)
	}
}

// ByStrategies orders the results by strategies terms.
func ByStrategies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStrategiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFlagStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlagInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FlagTable, FlagColumn),
	)
}
func newEnvironmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnvironmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EnvironmentTable, EnvironmentColumn),
	)
}
func newStrategiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StrategiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StrategiesTable, StrategiesColumn),
	)
}
