// Code generated by ent, DO NOT EDIT.

package flagenvironment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/felipekafuri/bandeira/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldLTE(FieldID, id))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldEnabled, v))
}

// FlagID applies equality check predicate on the "flag_id" field. It's identical to FlagIDEQ.
func FlagID(v int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldFlagID, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldEnvironmentID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldUpdatedAt, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNEQ(FieldEnabled, v))
}

// FlagIDEQ applies the EQ predicate on the "flag_id" field.
func FlagIDEQ(v int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldFlagID, v))
}

// FlagIDNEQ applies the NEQ predicate on the "flag_id" field.
func FlagIDNEQ(v int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNEQ(FieldFlagID, v))
}

// FlagIDIn applies the In predicate on the "flag_id" field.
func FlagIDIn(vs ...int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldIn(FieldFlagID, vs...))
}

// FlagIDNotIn applies the NotIn predicate on the "flag_id" field.
func FlagIDNotIn(vs ...int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNotIn(FieldFlagID, vs...))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...int) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasFlag applies the HasEdge predicate on the "flag" edge.
func HasFlag() predicate.FlagEnvironment {
	return predicate.FlagEnvironment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FlagTable, FlagColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlagWith applies the HasEdge predicate on the "flag" edge with a given conditions (other predicates).
func HasFlagWith(preds ...predicate.Flag) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(func(s *sql.Selector) {
		step := newFlagStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEnvironment applies the HasEdge predicate on the "environment" edge.
func HasEnvironment() predicate.FlagEnvironment {
	return predicate.FlagEnvironment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EnvironmentTable, EnvironmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnvironmentWith applies the HasEdge predicate on the "environment" edge with a given conditions (other predicates).
func HasEnvironmentWith(preds ...predicate.Environment) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(func(s *sql.Selector) {
		step := newEnvironmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStrategies applies the HasEdge predicate on the "strategies" edge.
func HasStrategies() predicate.FlagEnvironment {
	return predicate.FlagEnvironment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StrategiesTable, StrategiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStrategiesWith applies the HasEdge predicate on the "strategies" edge with a given conditions (other predicates).
func HasStrategiesWith(preds ...predicate.Strategy) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(func(s *sql.Selector) {
		step := newStrategiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FlagEnvironment) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FlagEnvironment) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FlagEnvironment) predicate.FlagEnvironment {
	return predicate.FlagEnvironment(sql.NotPredicates(p))
}
