// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felipekafuri/bandeira/ent/apitoken"
	"github.com/felipekafuri/bandeira/ent/project"
	"github.com/felipekafuri/bandeira/ent/user"
)

// ApiTokenCreate is the builder for creating a ApiToken entity.
type ApiTokenCreate struct {
	config
	mutation *ApiTokenMutation
	hooks    []Hook
}

// SetSecret sets the "secret" field.
func (_c *ApiTokenCreate) SetSecret(v string) *ApiTokenCreate {
	_c.mutation.SetSecret(v)
	return _c
}

// SetPlainToken sets the "plain_token" field.
func (_c *ApiTokenCreate) SetPlainToken(v string) *ApiTokenCreate {
	_c.mutation.SetPlainToken(v)
	return _c
}

// SetNillablePlainToken sets the "plain_token" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillablePlainToken(v *string) *ApiTokenCreate {
	if v != nil {
		_c.SetPlainToken(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ApiTokenCreate) SetName(v string) *ApiTokenCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTokenType sets the "token_type" field.
func (_c *ApiTokenCreate) SetTokenType(v apitoken.TokenType) *ApiTokenCreate {
	_c.mutation.SetTokenType(v)
	return _c
}

// SetEnvironment sets the "environment" field.
func (_c *ApiTokenCreate) SetEnvironment(v string) *ApiTokenCreate {
	_c.mutation.SetEnvironment(v)
	return _c
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableEnvironment(v *string) *ApiTokenCreate {
	if v != nil {
		_c.SetEnvironment(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *ApiTokenCreate) SetProjectID(v int) *ApiTokenCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ApiTokenCreate) SetCreatedBy(v int) *ApiTokenCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableCreatedBy(v *int) *ApiTokenCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApiTokenCreate) SetCreatedAt(v time.Time) *ApiTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableCreatedAt(v *time.Time) *ApiTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ApiTokenCreate) SetUpdatedAt(v time.Time) *ApiTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableUpdatedAt(v *time.Time) *ApiTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ApiTokenCreate) SetProject(v *Project) *ApiTokenCreate {
	return _c.SetProjectID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *ApiTokenCreate) SetCreatorID(id int) *ApiTokenCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableCreatorID(id *int) *ApiTokenCreate {
	if id != nil {
		_c = _c.SetCreatorID(*id)
	}
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *ApiTokenCreate) SetCreator(v *User) *ApiTokenCreate {
	return _c.SetCreatorID(v.ID)
}

// Mutation returns the ApiTokenMutation object of the builder.
func (_c *ApiTokenCreate) Mutation() *ApiTokenMutation {
	return _c.mutation
}

// Save creates the ApiToken in the database.
func (_c *ApiTokenCreate) Save(ctx context.Context) (*ApiToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApiTokenCreate) SaveX(ctx context.Context) *ApiToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApiTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApiTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApiTokenCreate) defaults() {
	if _, ok := _c.mutation.PlainToken(); !ok {
		v := apitoken.DefaultPlainToken
		_c.mutation.SetPlainToken(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apitoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apitoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApiTokenCreate) check() error {
	if _, ok := _c.mutation.Secret(); !ok {
		return &ValidationError{Name: "secret", err: errors.New(`ent: missing required field "ApiToken.secret"`)}
	}
	if _, ok := _c.mutation.PlainToken(); !ok {
		return &ValidationError{Name: "plain_token", err: errors.New(`ent: missing required field "ApiToken.plain_token"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ApiToken.name"`)}
	}
	if _, ok := _c.mutation.TokenType(); !ok {
		return &ValidationError{Name: "token_type", err: errors.New(`ent: missing required field "ApiToken.token_type"`)}
	}
	if v, ok := _c.mutation.TokenType(); ok {
		if err := apitoken.TokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "token_type", err: fmt.Errorf(`ent: validator failed for field "ApiToken.token_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ApiToken.project_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ApiToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ApiToken.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ApiToken.project"`)}
	}
	return nil
}

func (_c *ApiTokenCreate) sqlSave(ctx context.Context) (*ApiToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApiTokenCreate) createSpec() (*ApiToken, *sqlgraph.CreateSpec) {
	var (
		_node = &ApiToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apitoken.Table, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Secret(); ok {
		_spec.SetField(apitoken.FieldSecret, field.TypeString, value)
		_node.Secret = value
	}
	if value, ok := _c.mutation.PlainToken(); ok {
		_spec.SetField(apitoken.FieldPlainToken, field.TypeString, value)
		_node.PlainToken = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TokenType(); ok {
		_spec.SetField(apitoken.FieldTokenType, field.TypeEnum, value)
		_node.TokenType = value
	}
	if value, ok := _c.mutation.Environment(); ok {
		_spec.SetField(apitoken.FieldEnvironment, field.TypeString, value)
		_node.Environment = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apitoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apitoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.ProjectTable,
			Columns: []string{apitoken.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.CreatorTable,
			Columns: []string{apitoken.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ApiTokenCreateBulk is the builder for creating many ApiToken entities in bulk.
type ApiTokenCreateBulk struct {
	config
	err      error
	builders []*ApiTokenCreate
}

// Save creates the ApiToken entities in the database.
func (_c *ApiTokenCreateBulk) Save(ctx context.Context) ([]*ApiToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ApiToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApiTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApiTokenCreateBulk) SaveX(ctx context.Context) []*ApiToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApiTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApiTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
