// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felipekafuri/bandeira/ent/apitoken"
	"github.com/felipekafuri/bandeira/ent/predicate"
	"github.com/felipekafuri/bandeira/ent/project"
	"github.com/felipekafuri/bandeira/ent/user"
)

// ApiTokenUpdate is the builder for updating ApiToken entities.
type ApiTokenUpdate struct {
	config
	hooks    []Hook
	mutation *ApiTokenMutation
}

// Where appends a list predicates to the ApiTokenUpdate builder.
func (_u *ApiTokenUpdate) Where(ps ...predicate.ApiToken) *ApiTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSecret sets the "secret" field.
func (_u *ApiTokenUpdate) SetSecret(v string) *ApiTokenUpdate {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableSecret(v *string) *ApiTokenUpdate {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// SetPlainToken sets the "plain_token" field.
func (_u *ApiTokenUpdate) SetPlainToken(v string) *ApiTokenUpdate {
	_u.mutation.SetPlainToken(v)
	return _u
}

// SetNillablePlainToken sets the "plain_token" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillablePlainToken(v *string) *ApiTokenUpdate {
	if v != nil {
		_u.SetPlainToken(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ApiTokenUpdate) SetName(v string) *ApiTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableName(v *string) *ApiTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenType sets the "token_type" field.
func (_u *ApiTokenUpdate) SetTokenType(v apitoken.TokenType) *ApiTokenUpdate {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableTokenType(v *apitoken.TokenType) *ApiTokenUpdate {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// SetEnvironment sets the "environment" field.
func (_u *ApiTokenUpdate) SetEnvironment(v string) *ApiTokenUpdate {
	_u.mutation.SetEnvironment(v)
	return _u
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableEnvironment(v *string) *ApiTokenUpdate {
	if v != nil {
		_u.SetEnvironment(*v)
	}
	return _u
}

// ClearEnvironment clears the value of the "environment" field.
func (_u *ApiTokenUpdate) ClearEnvironment() *ApiTokenUpdate {
	_u.mutation.ClearEnvironment()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ApiTokenUpdate) SetProjectID(v int) *ApiTokenUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableProjectID(v *int) *ApiTokenUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ApiTokenUpdate) SetCreatedBy(v int) *ApiTokenUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableCreatedBy(v *int) *ApiTokenUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ApiTokenUpdate) ClearCreatedBy() *ApiTokenUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApiTokenUpdate) SetUpdatedAt(v time.Time) *ApiTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ApiTokenUpdate) SetProject(v *Project) *ApiTokenUpdate {
	return _u.SetProjectID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ApiTokenUpdate) SetCreatorID(id int) *ApiTokenUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableCreatorID(id *int) *ApiTokenUpdate {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ApiTokenUpdate) SetCreator(v *User) *ApiTokenUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the ApiTokenMutation object of the builder.
func (_u *ApiTokenUpdate) Mutation() *ApiTokenMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ApiTokenUpdate) ClearProject() *ApiTokenUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ApiTokenUpdate) ClearCreator() *ApiTokenUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApiTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apitoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiTokenUpdate) check() error {
	if v, ok := _u.mutation.TokenType(); ok {
		if err := apitoken.TokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "token_type", err: fmt.Errorf(`ent: validator failed for field "ApiToken.token_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiToken.project"`)
	}
	return nil
}

func (_u *ApiTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apitoken.Table, apitoken.Columns, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(apitoken.FieldSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlainToken(); ok {
		_spec.SetField(apitoken.FieldPlainToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(apitoken.FieldTokenType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Environment(); ok {
		_spec.SetField(apitoken.FieldEnvironment, field.TypeString, value)
	}
	if _u.mutation.EnvironmentCleared() {
		_spec.ClearField(apitoken.FieldEnvironment, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apitoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.ProjectTable,
			Columns: []string{apitoken.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.ProjectTable,
			Columns: []string{apitoken.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.CreatorTable,
			Columns: []string{apitoken.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.CreatorTable,
			Columns: []string{apitoken.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiTokenUpdateOne is the builder for updating a single ApiToken entity.
type ApiTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiTokenMutation
}

// SetSecret sets the "secret" field.
func (_u *ApiTokenUpdateOne) SetSecret(v string) *ApiTokenUpdateOne {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableSecret(v *string) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// SetPlainToken sets the "plain_token" field.
func (_u *ApiTokenUpdateOne) SetPlainToken(v string) *ApiTokenUpdateOne {
	_u.mutation.SetPlainToken(v)
	return _u
}

// SetNillablePlainToken sets the "plain_token" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillablePlainToken(v *string) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetPlainToken(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ApiTokenUpdateOne) SetName(v string) *ApiTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableName(v *string) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenType sets the "token_type" field.
func (_u *ApiTokenUpdateOne) SetTokenType(v apitoken.TokenType) *ApiTokenUpdateOne {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableTokenType(v *apitoken.TokenType) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// SetEnvironment sets the "environment" field.
func (_u *ApiTokenUpdateOne) SetEnvironment(v string) *ApiTokenUpdateOne {
	_u.mutation.SetEnvironment(v)
	return _u
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableEnvironment(v *string) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetEnvironment(*v)
	}
	return _u
}

// ClearEnvironment clears the value of the "environment" field.
func (_u *ApiTokenUpdateOne) ClearEnvironment() *ApiTokenUpdateOne {
	_u.mutation.ClearEnvironment()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ApiTokenUpdateOne) SetProjectID(v int) *ApiTokenUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableProjectID(v *int) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ApiTokenUpdateOne) SetCreatedBy(v int) *ApiTokenUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableCreatedBy(v *int) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ApiTokenUpdateOne) ClearCreatedBy() *ApiTokenUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApiTokenUpdateOne) SetUpdatedAt(v time.Time) *ApiTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ApiTokenUpdateOne) SetProject(v *Project) *ApiTokenUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ApiTokenUpdateOne) SetCreatorID(id int) *ApiTokenUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableCreatorID(id *int) *ApiTokenUpdateOne {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ApiTokenUpdateOne) SetCreator(v *User) *ApiTokenUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the ApiTokenMutation object of the builder.
func (_u *ApiTokenUpdateOne) Mutation() *ApiTokenMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ApiTokenUpdateOne) ClearProject() *ApiTokenUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ApiTokenUpdateOne) ClearCreator() *ApiTokenUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the ApiTokenUpdate builder.
func (_u *ApiTokenUpdateOne) Where(ps ...predicate.ApiToken) *ApiTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiTokenUpdateOne) Select(field string, fields ...string) *ApiTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiToken entity.
func (_u *ApiTokenUpdateOne) Save(ctx context.Context) (*ApiToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiTokenUpdateOne) SaveX(ctx context.Context) *ApiToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApiTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apitoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiTokenUpdateOne) check() error {
	if v, ok := _u.mutation.TokenType(); ok {
		if err := apitoken.TokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "token_type", err: fmt.Errorf(`ent: validator failed for field "ApiToken.token_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiToken.project"`)
	}
	return nil
}

func (_u *ApiTokenUpdateOne) sqlSave(ctx context.Context) (_node *ApiToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apitoken.Table, apitoken.Columns, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apitoken.FieldID)
		for _, f := range fields {
			if !apitoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apitoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(apitoken.FieldSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlainToken(); ok {
		_spec.SetField(apitoken.FieldPlainToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(apitoken.FieldTokenType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Environment(); ok {
		_spec.SetField(apitoken.FieldEnvironment, field.TypeString, value)
	}
	if _u.mutation.EnvironmentCleared() {
		_spec.ClearField(apitoken.FieldEnvironment, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apitoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.ProjectTable,
			Columns: []string{apitoken.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.ProjectTable,
			Columns: []string{apitoken.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.CreatorTable,
			Columns: []string{apitoken.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.CreatorTable,
			Columns: []string{apitoken.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
