// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felipekafuri/bandeira/ent/constraint"
	"github.com/felipekafuri/bandeira/ent/strategy"
)

// ConstraintCreate is the builder for creating a Constraint entity.
type ConstraintCreate struct {
	config
	mutation *ConstraintMutation
	hooks    []Hook
}

// SetContextName sets the "context_name" field.
func (_c *ConstraintCreate) SetContextName(v string) *ConstraintCreate {
	_c.mutation.SetContextName(v)
	return _c
}

// SetOperator sets the "operator" field.
func (_c *ConstraintCreate) SetOperator(v constraint.Operator) *ConstraintCreate {
	_c.mutation.SetOperator(v)
	return _c
}

// SetValues sets the "values" field.
func (_c *ConstraintCreate) SetValues(v []string) *ConstraintCreate {
	_c.mutation.SetValues(v)
	return _c
}

// SetInverted sets the "inverted" field.
func (_c *ConstraintCreate) SetInverted(v bool) *ConstraintCreate {
	_c.mutation.SetInverted(v)
	return _c
}

// SetNillableInverted sets the "inverted" field if the given value is not nil.
func (_c *ConstraintCreate) SetNillableInverted(v *bool) *ConstraintCreate {
	if v != nil {
		_c.SetInverted(*v)
	}
	return _c
}

// SetCaseInsensitive sets the "case_insensitive" field.
func (_c *ConstraintCreate) SetCaseInsensitive(v bool) *ConstraintCreate {
	_c.mutation.SetCaseInsensitive(v)
	return _c
}

// SetNillableCaseInsensitive sets the "case_insensitive" field if the given value is not nil.
func (_c *ConstraintCreate) SetNillableCaseInsensitive(v *bool) *ConstraintCreate {
	if v != nil {
		_c.SetCaseInsensitive(*v)
	}
	return _c
}

// SetStrategyID sets the "strategy_id" field.
func (_c *ConstraintCreate) SetStrategyID(v int) *ConstraintCreate {
	_c.mutation.SetStrategyID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConstraintCreate) SetCreatedAt(v time.Time) *ConstraintCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConstraintCreate) SetNillableCreatedAt(v *time.Time) *ConstraintCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConstraintCreate) SetUpdatedAt(v time.Time) *ConstraintCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConstraintCreate) SetNillableUpdatedAt(v *time.Time) *ConstraintCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStrategy sets the "strategy" edge to the Strategy entity.
func (_c *ConstraintCreate) SetStrategy(v *Strategy) *ConstraintCreate {
	return _c.SetStrategyID(v.ID)
}

// Mutation returns the ConstraintMutation object of the builder.
func (_c *ConstraintCreate) Mutation() *ConstraintMutation {
	return _c.mutation
}

// Save creates the Constraint in the database.
func (_c *ConstraintCreate) Save(ctx context.Context) (*Constraint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConstraintCreate) SaveX(ctx context.Context) *Constraint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConstraintCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConstraintCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConstraintCreate) defaults() {
	if _, ok := _c.mutation.Inverted(); !ok {
		v := constraint.DefaultInverted
		_c.mutation.SetInverted(v)
	}
	if _, ok := _c.mutation.CaseInsensitive(); !ok {
		v := constraint.DefaultCaseInsensitive
		_c.mutation.SetCaseInsensitive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := constraint.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := constraint.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConstraintCreate) check() error {
	if _, ok := _c.mutation.ContextName(); !ok {
		return &ValidationError{Name: "context_name", err: errors.New(`ent: missing required field "Constraint.context_name"`)}
	}
	if _, ok := _c.mutation.Operator(); !ok {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required field "Constraint.operator"`)}
	}
	if v, ok := _c.mutation.Operator(); ok {
		if err := constraint.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "Constraint.operator": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Values(); !ok {
		return &ValidationError{Name: "values", err: errors.New(`ent: missing required field "Constraint.values"`)}
	}
	if _, ok := _c.mutation.Inverted(); !ok {
		return &ValidationError{Name: "inverted", err: errors.New(`ent: missing required field "Constraint.inverted"`)}
	}
	if _, ok := _c.mutation.CaseInsensitive(); !ok {
		return &ValidationError{Name: "case_insensitive", err: errors.New(`ent: missing required field "Constraint.case_insensitive"`)}
	}
	if _, ok := _c.mutation.StrategyID(); !ok {
		return &ValidationError{Name: "strategy_id", err: errors.New(`ent: missing required field "Constraint.strategy_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Constraint.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Constraint.updated_at"`)}
	}
	if len(_c.mutation.StrategyIDs()) == 0 {
		return &ValidationError{Name: "strategy", err: errors.New(`ent: missing required edge "Constraint.strategy"`)}
	}
	return nil
}

func (_c *ConstraintCreate) sqlSave(ctx context.Context) (*Constraint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConstraintCreate) createSpec() (*Constraint, *sqlgraph.CreateSpec) {
	var (
		_node = &Constraint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(constraint.Table, sqlgraph.NewFieldSpec(constraint.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ContextName(); ok {
		_spec.SetField(constraint.FieldContextName, field.TypeString, value)
		_node.ContextName = value
	}
	if value, ok := _c.mutation.Operator(); ok {
		_spec.SetField(constraint.FieldOperator, field.TypeEnum, value)
		_node.Operator = value
	}
	if value, ok := _c.mutation.Values(); ok {
		_spec.SetField(constraint.FieldValues, field.TypeJSON, value)
		_node.Values = value
	}
	if value, ok := _c.mutation.Inverted(); ok {
		_spec.SetField(constraint.FieldInverted, field.TypeBool, value)
		_node.Inverted = value
	}
	if value, ok := _c.mutation.CaseInsensitive(); ok {
		_spec.SetField(constraint.FieldCaseInsensitive, field.TypeBool, value)
		_node.CaseInsensitive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(constraint.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(constraint.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.StrategyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   constraint.StrategyTable,
			Columns: []string{constraint.StrategyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StrategyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConstraintCreateBulk is the builder for creating many Constraint entities in bulk.
type ConstraintCreateBulk struct {
	config
	err      error
	builders []*ConstraintCreate
}

// Save creates the Constraint entities in the database.
func (_c *ConstraintCreateBulk) Save(ctx context.Context) ([]*Constraint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Constraint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConstraintMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConstraintCreateBulk) SaveX(ctx context.Context) []*Constraint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConstraintCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConstraintCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
