// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felipekafuri/bandeira/ent/environment"
	"github.com/felipekafuri/bandeira/ent/flagenvironment"
	"github.com/felipekafuri/bandeira/ent/predicate"
	"github.com/felipekafuri/bandeira/ent/project"
)

// EnvironmentUpdate is the builder for updating Environment entities.
type EnvironmentUpdate struct {
	config
	hooks    []Hook
	mutation *EnvironmentMutation
}

// Where appends a list predicates to the EnvironmentUpdate builder.
func (_u *EnvironmentUpdate) Where(ps ...predicate.Environment) *EnvironmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *EnvironmentUpdate) SetName(v string) *EnvironmentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableName(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *EnvironmentUpdate) SetType(v environment.Type) *EnvironmentUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableType(v *environment.Type) *EnvironmentUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *EnvironmentUpdate) SetSortOrder(v int) *EnvironmentUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableSortOrder(v *int) *EnvironmentUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *EnvironmentUpdate) AddSortOrder(v int) *EnvironmentUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EnvironmentUpdate) SetProjectID(v int) *EnvironmentUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableProjectID(v *int) *EnvironmentUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvironmentUpdate) SetUpdatedAt(v time.Time) *EnvironmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EnvironmentUpdate) SetProject(v *Project) *EnvironmentUpdate {
	return _u.SetProjectID(v.ID)
}

// AddFlagEnvironmentIDs adds the "flag_environments" edge to the FlagEnvironment entity by IDs.
func (_u *EnvironmentUpdate) AddFlagEnvironmentIDs(ids ...int) *EnvironmentUpdate {
	_u.mutation.AddFlagEnvironmentIDs(ids...)
	return _u
}

// AddFlagEnvironments adds the "flag_environments" edges to the FlagEnvironment entity.
func (_u *EnvironmentUpdate) AddFlagEnvironments(v ...*FlagEnvironment) *EnvironmentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlagEnvironmentIDs(ids...)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (_u *EnvironmentUpdate) Mutation() *EnvironmentMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EnvironmentUpdate) ClearProject() *EnvironmentUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearFlagEnvironments clears all "flag_environments" edges to the FlagEnvironment entity.
func (_u *EnvironmentUpdate) ClearFlagEnvironments() *EnvironmentUpdate {
	_u.mutation.ClearFlagEnvironments()
	return _u
}

// RemoveFlagEnvironmentIDs removes the "flag_environments" edge to FlagEnvironment entities by IDs.
func (_u *EnvironmentUpdate) RemoveFlagEnvironmentIDs(ids ...int) *EnvironmentUpdate {
	_u.mutation.RemoveFlagEnvironmentIDs(ids...)
	return _u
}

// RemoveFlagEnvironments removes "flag_environments" edges to FlagEnvironment entities.
func (_u *EnvironmentUpdate) RemoveFlagEnvironments(v ...*FlagEnvironment) *EnvironmentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlagEnvironmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnvironmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvironmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnvironmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvironmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvironmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := environment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvironmentUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := environment.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Environment.type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Environment.project"`)
	}
	return nil
}

func (_u *EnvironmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(environment.Table, environment.Columns, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(environment.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(environment.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(environment.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FlagEnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.FlagEnvironmentsTable,
			Columns: []string{environment.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlagEnvironmentsIDs(); len(nodes) > 0 && !_u.mutation.FlagEnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.FlagEnvironmentsTable,
			Columns: []string{environment.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlagEnvironmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.FlagEnvironmentsTable,
			Columns: []string{environment.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{environment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnvironmentUpdateOne is the builder for updating a single Environment entity.
type EnvironmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnvironmentMutation
}

// SetName sets the "name" field.
func (_u *EnvironmentUpdateOne) SetName(v string) *EnvironmentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableName(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *EnvironmentUpdateOne) SetType(v environment.Type) *EnvironmentUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableType(v *environment.Type) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *EnvironmentUpdateOne) SetSortOrder(v int) *EnvironmentUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableSortOrder(v *int) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *EnvironmentUpdateOne) AddSortOrder(v int) *EnvironmentUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EnvironmentUpdateOne) SetProjectID(v int) *EnvironmentUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableProjectID(v *int) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvironmentUpdateOne) SetUpdatedAt(v time.Time) *EnvironmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EnvironmentUpdateOne) SetProject(v *Project) *EnvironmentUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddFlagEnvironmentIDs adds the "flag_environments" edge to the FlagEnvironment entity by IDs.
func (_u *EnvironmentUpdateOne) AddFlagEnvironmentIDs(ids ...int) *EnvironmentUpdateOne {
	_u.mutation.AddFlagEnvironmentIDs(ids...)
	return _u
}

// AddFlagEnvironments adds the "flag_environments" edges to the FlagEnvironment entity.
func (_u *EnvironmentUpdateOne) AddFlagEnvironments(v ...*FlagEnvironment) *EnvironmentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlagEnvironmentIDs(ids...)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (_u *EnvironmentUpdateOne) Mutation() *EnvironmentMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EnvironmentUpdateOne) ClearProject() *EnvironmentUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearFlagEnvironments clears all "flag_environments" edges to the FlagEnvironment entity.
func (_u *EnvironmentUpdateOne) ClearFlagEnvironments() *EnvironmentUpdateOne {
	_u.mutation.ClearFlagEnvironments()
	return _u
}

// RemoveFlagEnvironmentIDs removes the "flag_environments" edge to FlagEnvironment entities by IDs.
func (_u *EnvironmentUpdateOne) RemoveFlagEnvironmentIDs(ids ...int) *EnvironmentUpdateOne {
	_u.mutation.RemoveFlagEnvironmentIDs(ids...)
	return _u
}

// RemoveFlagEnvironments removes "flag_environments" edges to FlagEnvironment entities.
func (_u *EnvironmentUpdateOne) RemoveFlagEnvironments(v ...*FlagEnvironment) *EnvironmentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlagEnvironmentIDs(ids...)
}

// Where appends a list predicates to the EnvironmentUpdate builder.
func (_u *EnvironmentUpdateOne) Where(ps ...predicate.Environment) *EnvironmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnvironmentUpdateOne) Select(field string, fields ...string) *EnvironmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Environment entity.
func (_u *EnvironmentUpdateOne) Save(ctx context.Context) (*Environment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvironmentUpdateOne) SaveX(ctx context.Context) *Environment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnvironmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvironmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvironmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := environment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvironmentUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := environment.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Environment.type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Environment.project"`)
	}
	return nil
}

func (_u *EnvironmentUpdateOne) sqlSave(ctx context.Context) (_node *Environment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(environment.Table, environment.Columns, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Environment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, environment.FieldID)
		for _, f := range fields {
			if !environment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != environment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(environment.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(environment.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(environment.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FlagEnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.FlagEnvironmentsTable,
			Columns: []string{environment.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlagEnvironmentsIDs(); len(nodes) > 0 && !_u.mutation.FlagEnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.FlagEnvironmentsTable,
			Columns: []string{environment.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlagEnvironmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.FlagEnvironmentsTable,
			Columns: []string{environment.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Environment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{environment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
