// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felipekafuri/bandeira/ent/environment"
	"github.com/felipekafuri/bandeira/ent/flag"
	"github.com/felipekafuri/bandeira/ent/flagenvironment"
	"github.com/felipekafuri/bandeira/ent/predicate"
	"github.com/felipekafuri/bandeira/ent/strategy"
)

// FlagEnvironmentUpdate is the builder for updating FlagEnvironment entities.
type FlagEnvironmentUpdate struct {
	config
	hooks    []Hook
	mutation *FlagEnvironmentMutation
}

// Where appends a list predicates to the FlagEnvironmentUpdate builder.
func (_u *FlagEnvironmentUpdate) Where(ps ...predicate.FlagEnvironment) *FlagEnvironmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *FlagEnvironmentUpdate) SetEnabled(v bool) *FlagEnvironmentUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *FlagEnvironmentUpdate) SetNillableEnabled(v *bool) *FlagEnvironmentUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetFlagID sets the "flag_id" field.
func (_u *FlagEnvironmentUpdate) SetFlagID(v int) *FlagEnvironmentUpdate {
	_u.mutation.SetFlagID(v)
	return _u
}

// SetNillableFlagID sets the "flag_id" field if the given value is not nil.
func (_u *FlagEnvironmentUpdate) SetNillableFlagID(v *int) *FlagEnvironmentUpdate {
	if v != nil {
		_u.SetFlagID(*v)
	}
	return _u
}

// SetEnvironmentID sets the "environment_id" field.
func (_u *FlagEnvironmentUpdate) SetEnvironmentID(v int) *FlagEnvironmentUpdate {
	_u.mutation.SetEnvironmentID(v)
	return _u
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_u *FlagEnvironmentUpdate) SetNillableEnvironmentID(v *int) *FlagEnvironmentUpdate {
	if v != nil {
		_u.SetEnvironmentID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlagEnvironmentUpdate) SetUpdatedAt(v time.Time) *FlagEnvironmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFlag sets the "flag" edge to the Flag entity.
func (_u *FlagEnvironmentUpdate) SetFlag(v *Flag) *FlagEnvironmentUpdate {
	return _u.SetFlagID(v.ID)
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_u *FlagEnvironmentUpdate) SetEnvironment(v *Environment) *FlagEnvironmentUpdate {
	return _u.SetEnvironmentID(v.ID)
}

// AddStrategyIDs adds the "strategies" edge to the Strategy entity by IDs.
func (_u *FlagEnvironmentUpdate) AddStrategyIDs(ids ...int) *FlagEnvironmentUpdate {
	_u.mutation.AddStrategyIDs(ids...)
	return _u
}

// AddStrategies adds the "strategies" edges to the Strategy entity.
func (_u *FlagEnvironmentUpdate) AddStrategies(v ...*Strategy) *FlagEnvironmentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStrategyIDs(ids...)
}

// Mutation returns the FlagEnvironmentMutation object of the builder.
func (_u *FlagEnvironmentUpdate) Mutation() *FlagEnvironmentMutation {
	return _u.mutation
}

// ClearFlag clears the "flag" edge to the Flag entity.
func (_u *FlagEnvironmentUpdate) ClearFlag() *FlagEnvironmentUpdate {
	_u.mutation.ClearFlag()
	return _u
}

// ClearEnvironment clears the "environment" edge to the Environment entity.
func (_u *FlagEnvironmentUpdate) ClearEnvironment() *FlagEnvironmentUpdate {
	_u.mutation.ClearEnvironment()
	return _u
}

// ClearStrategies clears all "strategies" edges to the Strategy entity.
func (_u *FlagEnvironmentUpdate) ClearStrategies() *FlagEnvironmentUpdate {
	_u.mutation.ClearStrategies()
	return _u
}

// RemoveStrategyIDs removes the "strategies" edge to Strategy entities by IDs.
func (_u *FlagEnvironmentUpdate) RemoveStrategyIDs(ids ...int) *FlagEnvironmentUpdate {
	_u.mutation.RemoveStrategyIDs(ids...)
	return _u
}

// RemoveStrategies removes "strategies" edges to Strategy entities.
func (_u *FlagEnvironmentUpdate) RemoveStrategies(v ...*Strategy) *FlagEnvironmentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStrategyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlagEnvironmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlagEnvironmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlagEnvironmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlagEnvironmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlagEnvironmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flagenvironment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlagEnvironmentUpdate) check() error {
	if _u.mutation.FlagCleared() && len(_u.mutation.FlagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlagEnvironment.flag"`)
	}
	if _u.mutation.EnvironmentCleared() && len(_u.mutation.EnvironmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlagEnvironment.environment"`)
	}
	return nil
}

func (_u *FlagEnvironmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flagenvironment.Table, flagenvironment.Columns, sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(flagenvironment.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flagenvironment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FlagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.FlagTable,
			Columns: []string{flagenvironment.FlagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.FlagTable,
			Columns: []string{flagenvironment.FlagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.EnvironmentTable,
			Columns: []string{flagenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.EnvironmentTable,
			Columns: []string{flagenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StrategiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flagenvironment.StrategiesTable,
			Columns: []string{flagenvironment.StrategiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStrategiesIDs(); len(nodes) > 0 && !_u.mutation.StrategiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flagenvironment.StrategiesTable,
			Columns: []string{flagenvironment.StrategiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StrategiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flagenvironment.StrategiesTable,
			Columns: []string{flagenvironment.StrategiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flagenvironment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlagEnvironmentUpdateOne is the builder for updating a single FlagEnvironment entity.
type FlagEnvironmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlagEnvironmentMutation
}

// SetEnabled sets the "enabled" field.
func (_u *FlagEnvironmentUpdateOne) SetEnabled(v bool) *FlagEnvironmentUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *FlagEnvironmentUpdateOne) SetNillableEnabled(v *bool) *FlagEnvironmentUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetFlagID sets the "flag_id" field.
func (_u *FlagEnvironmentUpdateOne) SetFlagID(v int) *FlagEnvironmentUpdateOne {
	_u.mutation.SetFlagID(v)
	return _u
}

// SetNillableFlagID sets the "flag_id" field if the given value is not nil.
func (_u *FlagEnvironmentUpdateOne) SetNillableFlagID(v *int) *FlagEnvironmentUpdateOne {
	if v != nil {
		_u.SetFlagID(*v)
	}
	return _u
}

// SetEnvironmentID sets the "environment_id" field.
func (_u *FlagEnvironmentUpdateOne) SetEnvironmentID(v int) *FlagEnvironmentUpdateOne {
	_u.mutation.SetEnvironmentID(v)
	return _u
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_u *FlagEnvironmentUpdateOne) SetNillableEnvironmentID(v *int) *FlagEnvironmentUpdateOne {
	if v != nil {
		_u.SetEnvironmentID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlagEnvironmentUpdateOne) SetUpdatedAt(v time.Time) *FlagEnvironmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFlag sets the "flag" edge to the Flag entity.
func (_u *FlagEnvironmentUpdateOne) SetFlag(v *Flag) *FlagEnvironmentUpdateOne {
	return _u.SetFlagID(v.ID)
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_u *FlagEnvironmentUpdateOne) SetEnvironment(v *Environment) *FlagEnvironmentUpdateOne {
	return _u.SetEnvironmentID(v.ID)
}

// AddStrategyIDs adds the "strategies" edge to the Strategy entity by IDs.
func (_u *FlagEnvironmentUpdateOne) AddStrategyIDs(ids ...int) *FlagEnvironmentUpdateOne {
	_u.mutation.AddStrategyIDs(ids...)
	return _u
}

// AddStrategies adds the "strategies" edges to the Strategy entity.
func (_u *FlagEnvironmentUpdateOne) AddStrategies(v ...*Strategy) *FlagEnvironmentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStrategyIDs(ids...)
}

// Mutation returns the FlagEnvironmentMutation object of the builder.
func (_u *FlagEnvironmentUpdateOne) Mutation() *FlagEnvironmentMutation {
	return _u.mutation
}

// ClearFlag clears the "flag" edge to the Flag entity.
func (_u *FlagEnvironmentUpdateOne) ClearFlag() *FlagEnvironmentUpdateOne {
	_u.mutation.ClearFlag()
	return _u
}

// ClearEnvironment clears the "environment" edge to the Environment entity.
func (_u *FlagEnvironmentUpdateOne) ClearEnvironment() *FlagEnvironmentUpdateOne {
	_u.mutation.ClearEnvironment()
	return _u
}

// ClearStrategies clears all "strategies" edges to the Strategy entity.
func (_u *FlagEnvironmentUpdateOne) ClearStrategies() *FlagEnvironmentUpdateOne {
	_u.mutation.ClearStrategies()
	return _u
}

// RemoveStrategyIDs removes the "strategies" edge to Strategy entities by IDs.
func (_u *FlagEnvironmentUpdateOne) RemoveStrategyIDs(ids ...int) *FlagEnvironmentUpdateOne {
	_u.mutation.RemoveStrategyIDs(ids...)
	return _u
}

// RemoveStrategies removes "strategies" edges to Strategy entities.
func (_u *FlagEnvironmentUpdateOne) RemoveStrategies(v ...*Strategy) *FlagEnvironmentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStrategyIDs(ids...)
}

// Where appends a list predicates to the FlagEnvironmentUpdate builder.
func (_u *FlagEnvironmentUpdateOne) Where(ps ...predicate.FlagEnvironment) *FlagEnvironmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlagEnvironmentUpdateOne) Select(field string, fields ...string) *FlagEnvironmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FlagEnvironment entity.
func (_u *FlagEnvironmentUpdateOne) Save(ctx context.Context) (*FlagEnvironment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlagEnvironmentUpdateOne) SaveX(ctx context.Context) *FlagEnvironment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlagEnvironmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlagEnvironmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlagEnvironmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flagenvironment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlagEnvironmentUpdateOne) check() error {
	if _u.mutation.FlagCleared() && len(_u.mutation.FlagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlagEnvironment.flag"`)
	}
	if _u.mutation.EnvironmentCleared() && len(_u.mutation.EnvironmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlagEnvironment.environment"`)
	}
	return nil
}

func (_u *FlagEnvironmentUpdateOne) sqlSave(ctx context.Context) (_node *FlagEnvironment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flagenvironment.Table, flagenvironment.Columns, sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FlagEnvironment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flagenvironment.FieldID)
		for _, f := range fields {
			if !flagenvironment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flagenvironment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(flagenvironment.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flagenvironment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FlagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.FlagTable,
			Columns: []string{flagenvironment.FlagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.FlagTable,
			Columns: []string{flagenvironment.FlagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.EnvironmentTable,
			Columns: []string{flagenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.EnvironmentTable,
			Columns: []string{flagenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StrategiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flagenvironment.StrategiesTable,
			Columns: []string{flagenvironment.StrategiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStrategiesIDs(); len(nodes) > 0 && !_u.mutation.StrategiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flagenvironment.StrategiesTable,
			Columns: []string{flagenvironment.StrategiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StrategiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flagenvironment.StrategiesTable,
			Columns: []string{flagenvironment.StrategiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FlagEnvironment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flagenvironment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
