// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/felipekafuri/bandeira/ent/environment"
	"github.com/felipekafuri/bandeira/ent/flag"
	"github.com/felipekafuri/bandeira/ent/flagenvironment"
)

// FlagEnvironment is the model entity for the FlagEnvironment schema.
type FlagEnvironment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// FlagID holds the value of the "flag_id" field.
	FlagID int `json:"flag_id,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID int `json:"environment_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlagEnvironmentQuery when eager-loading is set.
	Edges        FlagEnvironmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FlagEnvironmentEdges holds the relations/edges for other nodes in the graph.
type FlagEnvironmentEdges struct {
	// Flag holds the value of the flag edge.
	Flag *Flag `json:"flag,omitempty"`
	// Environment holds the value of the environment edge.
	Environment *Environment `json:"environment,omitempty"`
	// Strategies holds the value of the strategies edge.
	Strategies []*Strategy `json:"strategies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// FlagOrErr returns the Flag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlagEnvironmentEdges) FlagOrErr() (*Flag, error) {
	if e.Flag != nil {
		return e.Flag, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: flag.Label}
	}
	return nil, &NotLoadedError{edge: "flag"}
}

// EnvironmentOrErr returns the Environment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlagEnvironmentEdges) EnvironmentOrErr() (*Environment, error) {
	if e.Environment != nil {
		return e.Environment, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: environment.Label}
	}
	return nil, &NotLoadedError{edge: "environment"}
}

// StrategiesOrErr returns the Strategies value or an error if the edge
// was not loaded in eager-loading.
func (e FlagEnvironmentEdges) StrategiesOrErr() ([]*Strategy, error) {
	if e.loadedTypes[2] {
		return e.Strategies, nil
	}
	return nil, &NotLoadedError{edge: "strategies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FlagEnvironment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flagenvironment.FieldEnabled:
			values[i] = new(sql.NullBool)
		case flagenvironment.FieldID, flagenvironment.FieldFlagID, flagenvironment.FieldEnvironmentID:
			values[i] = new(sql.NullInt64)
		case flagenvironment.FieldCreatedAt, flagenvironment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FlagEnvironment fields.
func (_m *FlagEnvironment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flagenvironment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case flagenvironment.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case flagenvironment.FieldFlagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field flag_id", values[i])
			} else if value.Valid {
				_m.FlagID = int(value.Int64)
			}
		case flagenvironment.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				_m.EnvironmentID = int(value.Int64)
			}
		case flagenvironment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case flagenvironment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FlagEnvironment.
// This includes values selected through modifiers, order, etc.
func (_m *FlagEnvironment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFlag queries the "flag" edge of the FlagEnvironment entity.
func (_m *FlagEnvironment) QueryFlag() *FlagQuery {
	return NewFlagEnvironmentClient(_m.config).QueryFlag(_m)
}

// QueryEnvironment queries the "environment" edge of the FlagEnvironment entity.
func (_m *FlagEnvironment) QueryEnvironment() *EnvironmentQuery {
	return NewFlagEnvironmentClient(_m.config).QueryEnvironment(_m)
}

// QueryStrategies queries the "strategies" edge of the FlagEnvironment entity.
func (_m *FlagEnvironment) QueryStrategies() *StrategyQuery {
	return NewFlagEnvironmentClient(_m.config).QueryStrategies(_m)
}

// Update returns a builder for updating this FlagEnvironment.
// Note that you need to call FlagEnvironment.Unwrap() before calling this method if this FlagEnvironment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FlagEnvironment) Update() *FlagEnvironmentUpdateOne {
	return NewFlagEnvironmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FlagEnvironment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FlagEnvironment) Unwrap() *FlagEnvironment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FlagEnvironment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FlagEnvironment) String() string {
	var builder strings.Builder
	builder.WriteString("FlagEnvironment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("flag_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FlagID))
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnvironmentID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FlagEnvironments is a parsable slice of FlagEnvironment.
type FlagEnvironments []*FlagEnvironment
