// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felipekafuri/bandeira/ent/flag"
	"github.com/felipekafuri/bandeira/ent/flagenvironment"
	"github.com/felipekafuri/bandeira/ent/predicate"
	"github.com/felipekafuri/bandeira/ent/project"
)

// FlagUpdate is the builder for updating Flag entities.
type FlagUpdate struct {
	config
	hooks    []Hook
	mutation *FlagMutation
}

// Where appends a list predicates to the FlagUpdate builder.
func (_u *FlagUpdate) Where(ps ...predicate.Flag) *FlagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *FlagUpdate) SetName(v string) *FlagUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FlagUpdate) SetNillableName(v *string) *FlagUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FlagUpdate) SetDescription(v string) *FlagUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FlagUpdate) SetNillableDescription(v *string) *FlagUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FlagUpdate) ClearDescription() *FlagUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetFlagType sets the "flag_type" field.
func (_u *FlagUpdate) SetFlagType(v flag.FlagType) *FlagUpdate {
	_u.mutation.SetFlagType(v)
	return _u
}

// SetNillableFlagType sets the "flag_type" field if the given value is not nil.
func (_u *FlagUpdate) SetNillableFlagType(v *flag.FlagType) *FlagUpdate {
	if v != nil {
		_u.SetFlagType(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *FlagUpdate) SetProjectID(v int) *FlagUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *FlagUpdate) SetNillableProjectID(v *int) *FlagUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlagUpdate) SetUpdatedAt(v time.Time) *FlagUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *FlagUpdate) SetProject(v *Project) *FlagUpdate {
	return _u.SetProjectID(v.ID)
}

// AddFlagEnvironmentIDs adds the "flag_environments" edge to the FlagEnvironment entity by IDs.
func (_u *FlagUpdate) AddFlagEnvironmentIDs(ids ...int) *FlagUpdate {
	_u.mutation.AddFlagEnvironmentIDs(ids...)
	return _u
}

// AddFlagEnvironments adds the "flag_environments" edges to the FlagEnvironment entity.
func (_u *FlagUpdate) AddFlagEnvironments(v ...*FlagEnvironment) *FlagUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlagEnvironmentIDs(ids...)
}

// Mutation returns the FlagMutation object of the builder.
func (_u *FlagUpdate) Mutation() *FlagMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *FlagUpdate) ClearProject() *FlagUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearFlagEnvironments clears all "flag_environments" edges to the FlagEnvironment entity.
func (_u *FlagUpdate) ClearFlagEnvironments() *FlagUpdate {
	_u.mutation.ClearFlagEnvironments()
	return _u
}

// RemoveFlagEnvironmentIDs removes the "flag_environments" edge to FlagEnvironment entities by IDs.
func (_u *FlagUpdate) RemoveFlagEnvironmentIDs(ids ...int) *FlagUpdate {
	_u.mutation.RemoveFlagEnvironmentIDs(ids...)
	return _u
}

// RemoveFlagEnvironments removes "flag_environments" edges to FlagEnvironment entities.
func (_u *FlagUpdate) RemoveFlagEnvironments(v ...*FlagEnvironment) *FlagUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlagEnvironmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlagUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlagUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlagUpdate) check() error {
	if v, ok := _u.mutation.FlagType(); ok {
		if err := flag.FlagTypeValidator(v); err != nil {
			return &ValidationError{Name: "flag_type", err: fmt.Errorf(`ent: validator failed for field "Flag.flag_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flag.project"`)
	}
	return nil
}

func (_u *FlagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flag.Table, flag.Columns, sqlgraph.NewFieldSpec(flag.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(flag.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(flag.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(flag.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.FlagType(); ok {
		_spec.SetField(flag.FieldFlagType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flag.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flag.ProjectTable,
			Columns: []string{flag.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flag.ProjectTable,
			Columns: []string{flag.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FlagEnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flag.FlagEnvironmentsTable,
			Columns: []string{flag.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlagEnvironmentsIDs(); len(nodes) > 0 && !_u.mutation.FlagEnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flag.FlagEnvironmentsTable,
			Columns: []string{flag.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlagEnvironmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flag.FlagEnvironmentsTable,
			Columns: []string{flag.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlagUpdateOne is the builder for updating a single Flag entity.
type FlagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlagMutation
}

// SetName sets the "name" field.
func (_u *FlagUpdateOne) SetName(v string) *FlagUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FlagUpdateOne) SetNillableName(v *string) *FlagUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FlagUpdateOne) SetDescription(v string) *FlagUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FlagUpdateOne) SetNillableDescription(v *string) *FlagUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FlagUpdateOne) ClearDescription() *FlagUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetFlagType sets the "flag_type" field.
func (_u *FlagUpdateOne) SetFlagType(v flag.FlagType) *FlagUpdateOne {
	_u.mutation.SetFlagType(v)
	return _u
}

// SetNillableFlagType sets the "flag_type" field if the given value is not nil.
func (_u *FlagUpdateOne) SetNillableFlagType(v *flag.FlagType) *FlagUpdateOne {
	if v != nil {
		_u.SetFlagType(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *FlagUpdateOne) SetProjectID(v int) *FlagUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *FlagUpdateOne) SetNillableProjectID(v *int) *FlagUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlagUpdateOne) SetUpdatedAt(v time.Time) *FlagUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *FlagUpdateOne) SetProject(v *Project) *FlagUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddFlagEnvironmentIDs adds the "flag_environments" edge to the FlagEnvironment entity by IDs.
func (_u *FlagUpdateOne) AddFlagEnvironmentIDs(ids ...int) *FlagUpdateOne {
	_u.mutation.AddFlagEnvironmentIDs(ids...)
	return _u
}

// AddFlagEnvironments adds the "flag_environments" edges to the FlagEnvironment entity.
func (_u *FlagUpdateOne) AddFlagEnvironments(v ...*FlagEnvironment) *FlagUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlagEnvironmentIDs(ids...)
}

// Mutation returns the FlagMutation object of the builder.
func (_u *FlagUpdateOne) Mutation() *FlagMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *FlagUpdateOne) ClearProject() *FlagUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearFlagEnvironments clears all "flag_environments" edges to the FlagEnvironment entity.
func (_u *FlagUpdateOne) ClearFlagEnvironments() *FlagUpdateOne {
	_u.mutation.ClearFlagEnvironments()
	return _u
}

// RemoveFlagEnvironmentIDs removes the "flag_environments" edge to FlagEnvironment entities by IDs.
func (_u *FlagUpdateOne) RemoveFlagEnvironmentIDs(ids ...int) *FlagUpdateOne {
	_u.mutation.RemoveFlagEnvironmentIDs(ids...)
	return _u
}

// RemoveFlagEnvironments removes "flag_environments" edges to FlagEnvironment entities.
func (_u *FlagUpdateOne) RemoveFlagEnvironments(v ...*FlagEnvironment) *FlagUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlagEnvironmentIDs(ids...)
}

// Where appends a list predicates to the FlagUpdate builder.
func (_u *FlagUpdateOne) Where(ps ...predicate.Flag) *FlagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlagUpdateOne) Select(field string, fields ...string) *FlagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Flag entity.
func (_u *FlagUpdateOne) Save(ctx context.Context) (*Flag, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlagUpdateOne) SaveX(ctx context.Context) *Flag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlagUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlagUpdateOne) check() error {
	if v, ok := _u.mutation.FlagType(); ok {
		if err := flag.FlagTypeValidator(v); err != nil {
			return &ValidationError{Name: "flag_type", err: fmt.Errorf(`ent: validator failed for field "Flag.flag_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flag.project"`)
	}
	return nil
}

func (_u *FlagUpdateOne) sqlSave(ctx context.Context) (_node *Flag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flag.Table, flag.Columns, sqlgraph.NewFieldSpec(flag.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flag.FieldID)
		for _, f := range fields {
			if !flag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(flag.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(flag.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(flag.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.FlagType(); ok {
		_spec.SetField(flag.FieldFlagType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flag.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flag.ProjectTable,
			Columns: []string{flag.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flag.ProjectTable,
			Columns: []string{flag.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FlagEnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flag.FlagEnvironmentsTable,
			Columns: []string{flag.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlagEnvironmentsIDs(); len(nodes) > 0 && !_u.mutation.FlagEnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flag.FlagEnvironmentsTable,
			Columns: []string{flag.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlagEnvironmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flag.FlagEnvironmentsTable,
			Columns: []string{flag.FlagEnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Flag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
