// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/felipekafuri/bandeira/ent/flag"
	"github.com/felipekafuri/bandeira/ent/project"
)

// Flag is the model entity for the Flag schema.
type Flag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// FlagType holds the value of the "flag_type" field.
	FlagType flag.FlagType `json:"flag_type,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int `json:"project_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlagQuery when eager-loading is set.
	Edges        FlagEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FlagEdges holds the relations/edges for other nodes in the graph.
type FlagEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// FlagEnvironments holds the value of the flag_environments edge.
	FlagEnvironments []*FlagEnvironment `json:"flag_environments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlagEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// FlagEnvironmentsOrErr returns the FlagEnvironments value or an error if the edge
// was not loaded in eager-loading.
func (e FlagEdges) FlagEnvironmentsOrErr() ([]*FlagEnvironment, error) {
	if e.loadedTypes[1] {
		return e.FlagEnvironments, nil
	}
	return nil, &NotLoadedError{edge: "flag_environments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Flag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flag.FieldID, flag.FieldProjectID:
			values[i] = new(sql.NullInt64)
		case flag.FieldName, flag.FieldDescription, flag.FieldFlagType:
			values[i] = new(sql.NullString)
		case flag.FieldCreatedAt, flag.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Flag fields.
func (_m *Flag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case flag.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case flag.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case flag.FieldFlagType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flag_type", values[i])
			} else if value.Valid {
				_m.FlagType = flag.FlagType(value.String)
			}
		case flag.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case flag.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case flag.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Flag.
// This includes values selected through modifiers, order, etc.
func (_m *Flag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Flag entity.
func (_m *Flag) QueryProject() *ProjectQuery {
	return NewFlagClient(_m.config).QueryProject(_m)
}

// QueryFlagEnvironments queries the "flag_environments" edge of the Flag entity.
func (_m *Flag) QueryFlagEnvironments() *FlagEnvironmentQuery {
	return NewFlagClient(_m.config).QueryFlagEnvironments(_m)
}

// Update returns a builder for updating this Flag.
// Note that you need to call Flag.Unwrap() before calling this method if this Flag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Flag) Update() *FlagUpdateOne {
	return NewFlagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Flag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Flag) Unwrap() *Flag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Flag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Flag) String() string {
	var builder strings.Builder
	builder.WriteString("Flag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("flag_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.FlagType))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Flags is a parsable slice of Flag.
type Flags []*Flag
