// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felipekafuri/bandeira/ent/environment"
	"github.com/felipekafuri/bandeira/ent/flag"
	"github.com/felipekafuri/bandeira/ent/flagenvironment"
	"github.com/felipekafuri/bandeira/ent/strategy"
)

// FlagEnvironmentCreate is the builder for creating a FlagEnvironment entity.
type FlagEnvironmentCreate struct {
	config
	mutation *FlagEnvironmentMutation
	hooks    []Hook
}

// SetEnabled sets the "enabled" field.
func (_c *FlagEnvironmentCreate) SetEnabled(v bool) *FlagEnvironmentCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *FlagEnvironmentCreate) SetNillableEnabled(v *bool) *FlagEnvironmentCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetFlagID sets the "flag_id" field.
func (_c *FlagEnvironmentCreate) SetFlagID(v int) *FlagEnvironmentCreate {
	_c.mutation.SetFlagID(v)
	return _c
}

// SetEnvironmentID sets the "environment_id" field.
func (_c *FlagEnvironmentCreate) SetEnvironmentID(v int) *FlagEnvironmentCreate {
	_c.mutation.SetEnvironmentID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FlagEnvironmentCreate) SetCreatedAt(v time.Time) *FlagEnvironmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FlagEnvironmentCreate) SetNillableCreatedAt(v *time.Time) *FlagEnvironmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FlagEnvironmentCreate) SetUpdatedAt(v time.Time) *FlagEnvironmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FlagEnvironmentCreate) SetNillableUpdatedAt(v *time.Time) *FlagEnvironmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFlag sets the "flag" edge to the Flag entity.
func (_c *FlagEnvironmentCreate) SetFlag(v *Flag) *FlagEnvironmentCreate {
	return _c.SetFlagID(v.ID)
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_c *FlagEnvironmentCreate) SetEnvironment(v *Environment) *FlagEnvironmentCreate {
	return _c.SetEnvironmentID(v.ID)
}

// AddStrategyIDs adds the "strategies" edge to the Strategy entity by IDs.
func (_c *FlagEnvironmentCreate) AddStrategyIDs(ids ...int) *FlagEnvironmentCreate {
	_c.mutation.AddStrategyIDs(ids...)
	return _c
}

// AddStrategies adds the "strategies" edges to the Strategy entity.
func (_c *FlagEnvironmentCreate) AddStrategies(v ...*Strategy) *FlagEnvironmentCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStrategyIDs(ids...)
}

// Mutation returns the FlagEnvironmentMutation object of the builder.
func (_c *FlagEnvironmentCreate) Mutation() *FlagEnvironmentMutation {
	return _c.mutation
}

// Save creates the FlagEnvironment in the database.
func (_c *FlagEnvironmentCreate) Save(ctx context.Context) (*FlagEnvironment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FlagEnvironmentCreate) SaveX(ctx context.Context) *FlagEnvironment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlagEnvironmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlagEnvironmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FlagEnvironmentCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := flagenvironment.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := flagenvironment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := flagenvironment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FlagEnvironmentCreate) check() error {
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "FlagEnvironment.enabled"`)}
	}
	if _, ok := _c.mutation.FlagID(); !ok {
		return &ValidationError{Name: "flag_id", err: errors.New(`ent: missing required field "FlagEnvironment.flag_id"`)}
	}
	if _, ok := _c.mutation.EnvironmentID(); !ok {
		return &ValidationError{Name: "environment_id", err: errors.New(`ent: missing required field "FlagEnvironment.environment_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FlagEnvironment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FlagEnvironment.updated_at"`)}
	}
	if len(_c.mutation.FlagIDs()) == 0 {
		return &ValidationError{Name: "flag", err: errors.New(`ent: missing required edge "FlagEnvironment.flag"`)}
	}
	if len(_c.mutation.EnvironmentIDs()) == 0 {
		return &ValidationError{Name: "environment", err: errors.New(`ent: missing required edge "FlagEnvironment.environment"`)}
	}
	return nil
}

func (_c *FlagEnvironmentCreate) sqlSave(ctx context.Context) (*FlagEnvironment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FlagEnvironmentCreate) createSpec() (*FlagEnvironment, *sqlgraph.CreateSpec) {
	var (
		_node = &FlagEnvironment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(flagenvironment.Table, sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(flagenvironment.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(flagenvironment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(flagenvironment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.FlagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.FlagTable,
			Columns: []string{flagenvironment.FlagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FlagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flagenvironment.EnvironmentTable,
			Columns: []string{flagenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EnvironmentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StrategiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flagenvironment.StrategiesTable,
			Columns: []string{flagenvironment.StrategiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FlagEnvironmentCreateBulk is the builder for creating many FlagEnvironment entities in bulk.
type FlagEnvironmentCreateBulk struct {
	config
	err      error
	builders []*FlagEnvironmentCreate
}

// Save creates the FlagEnvironment entities in the database.
func (_c *FlagEnvironmentCreateBulk) Save(ctx context.Context) ([]*FlagEnvironment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FlagEnvironment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlagEnvironmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FlagEnvironmentCreateBulk) SaveX(ctx context.Context) []*FlagEnvironment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlagEnvironmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlagEnvironmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
