// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felipekafuri/bandeira/ent/constraint"
	"github.com/felipekafuri/bandeira/ent/flagenvironment"
	"github.com/felipekafuri/bandeira/ent/predicate"
	"github.com/felipekafuri/bandeira/ent/strategy"
)

// StrategyUpdate is the builder for updating Strategy entities.
type StrategyUpdate struct {
	config
	hooks    []Hook
	mutation *StrategyMutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (_u *StrategyUpdate) Where(ps ...predicate.Strategy) *StrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StrategyUpdate) SetName(v string) *StrategyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableName(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *StrategyUpdate) SetParameters(v map[string]interface{}) *StrategyUpdate {
	_u.mutation.SetParameters(v)
	return _u
}

// ClearParameters clears the value of the "parameters" field.
func (_u *StrategyUpdate) ClearParameters() *StrategyUpdate {
	_u.mutation.ClearParameters()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *StrategyUpdate) SetSortOrder(v int) *StrategyUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableSortOrder(v *int) *StrategyUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *StrategyUpdate) AddSortOrder(v int) *StrategyUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetFlagEnvironmentID sets the "flag_environment_id" field.
func (_u *StrategyUpdate) SetFlagEnvironmentID(v int) *StrategyUpdate {
	_u.mutation.SetFlagEnvironmentID(v)
	return _u
}

// SetNillableFlagEnvironmentID sets the "flag_environment_id" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableFlagEnvironmentID(v *int) *StrategyUpdate {
	if v != nil {
		_u.SetFlagEnvironmentID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StrategyUpdate) SetUpdatedAt(v time.Time) *StrategyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFlagEnvironment sets the "flag_environment" edge to the FlagEnvironment entity.
func (_u *StrategyUpdate) SetFlagEnvironment(v *FlagEnvironment) *StrategyUpdate {
	return _u.SetFlagEnvironmentID(v.ID)
}

// AddConstraintIDs adds the "constraints" edge to the Constraint entity by IDs.
func (_u *StrategyUpdate) AddConstraintIDs(ids ...int) *StrategyUpdate {
	_u.mutation.AddConstraintIDs(ids...)
	return _u
}

// AddConstraints adds the "constraints" edges to the Constraint entity.
func (_u *StrategyUpdate) AddConstraints(v ...*Constraint) *StrategyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConstraintIDs(ids...)
}

// Mutation returns the StrategyMutation object of the builder.
func (_u *StrategyUpdate) Mutation() *StrategyMutation {
	return _u.mutation
}

// ClearFlagEnvironment clears the "flag_environment" edge to the FlagEnvironment entity.
func (_u *StrategyUpdate) ClearFlagEnvironment() *StrategyUpdate {
	_u.mutation.ClearFlagEnvironment()
	return _u
}

// ClearConstraints clears all "constraints" edges to the Constraint entity.
func (_u *StrategyUpdate) ClearConstraints() *StrategyUpdate {
	_u.mutation.ClearConstraints()
	return _u
}

// RemoveConstraintIDs removes the "constraints" edge to Constraint entities by IDs.
func (_u *StrategyUpdate) RemoveConstraintIDs(ids ...int) *StrategyUpdate {
	_u.mutation.RemoveConstraintIDs(ids...)
	return _u
}

// RemoveConstraints removes "constraints" edges to Constraint entities.
func (_u *StrategyUpdate) RemoveConstraints(v ...*Constraint) *StrategyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConstraintIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StrategyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StrategyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := strategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StrategyUpdate) check() error {
	if _u.mutation.FlagEnvironmentCleared() && len(_u.mutation.FlagEnvironmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Strategy.flag_environment"`)
	}
	return nil
}

func (_u *StrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(strategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(strategy.FieldParameters, field.TypeJSON, value)
	}
	if _u.mutation.ParametersCleared() {
		_spec.ClearField(strategy.FieldParameters, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(strategy.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(strategy.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(strategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FlagEnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   strategy.FlagEnvironmentTable,
			Columns: []string{strategy.FlagEnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlagEnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   strategy.FlagEnvironmentTable,
			Columns: []string{strategy.FlagEnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConstraintsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   strategy.ConstraintsTable,
			Columns: []string{strategy.ConstraintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(constraint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConstraintsIDs(); len(nodes) > 0 && !_u.mutation.ConstraintsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   strategy.ConstraintsTable,
			Columns: []string{strategy.ConstraintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(constraint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConstraintsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   strategy.ConstraintsTable,
			Columns: []string{strategy.ConstraintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(constraint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StrategyUpdateOne is the builder for updating a single Strategy entity.
type StrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StrategyMutation
}

// SetName sets the "name" field.
func (_u *StrategyUpdateOne) SetName(v string) *StrategyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableName(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *StrategyUpdateOne) SetParameters(v map[string]interface{}) *StrategyUpdateOne {
	_u.mutation.SetParameters(v)
	return _u
}

// ClearParameters clears the value of the "parameters" field.
func (_u *StrategyUpdateOne) ClearParameters() *StrategyUpdateOne {
	_u.mutation.ClearParameters()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *StrategyUpdateOne) SetSortOrder(v int) *StrategyUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableSortOrder(v *int) *StrategyUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *StrategyUpdateOne) AddSortOrder(v int) *StrategyUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetFlagEnvironmentID sets the "flag_environment_id" field.
func (_u *StrategyUpdateOne) SetFlagEnvironmentID(v int) *StrategyUpdateOne {
	_u.mutation.SetFlagEnvironmentID(v)
	return _u
}

// SetNillableFlagEnvironmentID sets the "flag_environment_id" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableFlagEnvironmentID(v *int) *StrategyUpdateOne {
	if v != nil {
		_u.SetFlagEnvironmentID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StrategyUpdateOne) SetUpdatedAt(v time.Time) *StrategyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFlagEnvironment sets the "flag_environment" edge to the FlagEnvironment entity.
func (_u *StrategyUpdateOne) SetFlagEnvironment(v *FlagEnvironment) *StrategyUpdateOne {
	return _u.SetFlagEnvironmentID(v.ID)
}

// AddConstraintIDs adds the "constraints" edge to the Constraint entity by IDs.
func (_u *StrategyUpdateOne) AddConstraintIDs(ids ...int) *StrategyUpdateOne {
	_u.mutation.AddConstraintIDs(ids...)
	return _u
}

// AddConstraints adds the "constraints" edges to the Constraint entity.
func (_u *StrategyUpdateOne) AddConstraints(v ...*Constraint) *StrategyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConstraintIDs(ids...)
}

// Mutation returns the StrategyMutation object of the builder.
func (_u *StrategyUpdateOne) Mutation() *StrategyMutation {
	return _u.mutation
}

// ClearFlagEnvironment clears the "flag_environment" edge to the FlagEnvironment entity.
func (_u *StrategyUpdateOne) ClearFlagEnvironment() *StrategyUpdateOne {
	_u.mutation.ClearFlagEnvironment()
	return _u
}

// ClearConstraints clears all "constraints" edges to the Constraint entity.
func (_u *StrategyUpdateOne) ClearConstraints() *StrategyUpdateOne {
	_u.mutation.ClearConstraints()
	return _u
}

// RemoveConstraintIDs removes the "constraints" edge to Constraint entities by IDs.
func (_u *StrategyUpdateOne) RemoveConstraintIDs(ids ...int) *StrategyUpdateOne {
	_u.mutation.RemoveConstraintIDs(ids...)
	return _u
}

// RemoveConstraints removes "constraints" edges to Constraint entities.
func (_u *StrategyUpdateOne) RemoveConstraints(v ...*Constraint) *StrategyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConstraintIDs(ids...)
}

// Where appends a list predicates to the StrategyUpdate builder.
func (_u *StrategyUpdateOne) Where(ps ...predicate.Strategy) *StrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StrategyUpdateOne) Select(field string, fields ...string) *StrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Strategy entity.
func (_u *StrategyUpdateOne) Save(ctx context.Context) (*Strategy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyUpdateOne) SaveX(ctx context.Context) *Strategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StrategyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := strategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StrategyUpdateOne) check() error {
	if _u.mutation.FlagEnvironmentCleared() && len(_u.mutation.FlagEnvironmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Strategy.flag_environment"`)
	}
	return nil
}

func (_u *StrategyUpdateOne) sqlSave(ctx context.Context) (_node *Strategy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Strategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, strategy.FieldID)
		for _, f := range fields {
			if !strategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != strategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(strategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(strategy.FieldParameters, field.TypeJSON, value)
	}
	if _u.mutation.ParametersCleared() {
		_spec.ClearField(strategy.FieldParameters, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(strategy.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(strategy.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(strategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FlagEnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   strategy.FlagEnvironmentTable,
			Columns: []string{strategy.FlagEnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlagEnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   strategy.FlagEnvironmentTable,
			Columns: []string{strategy.FlagEnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagenvironment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConstraintsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   strategy.ConstraintsTable,
			Columns: []string{strategy.ConstraintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(constraint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConstraintsIDs(); len(nodes) > 0 && !_u.mutation.ConstraintsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   strategy.ConstraintsTable,
			Columns: []string{strategy.ConstraintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(constraint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConstraintsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   strategy.ConstraintsTable,
			Columns: []string{strategy.ConstraintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(constraint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Strategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
