// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/felipekafuri/bandeira/ent/flagenvironment"
	"github.com/felipekafuri/bandeira/ent/strategy"
)

// Strategy is the model entity for the Strategy schema.
type Strategy struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Parameters holds the value of the "parameters" field.
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// FlagEnvironmentID holds the value of the "flag_environment_id" field.
	FlagEnvironmentID int `json:"flag_environment_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StrategyQuery when eager-loading is set.
	Edges        StrategyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StrategyEdges holds the relations/edges for other nodes in the graph.
type StrategyEdges struct {
	// FlagEnvironment holds the value of the flag_environment edge.
	FlagEnvironment *FlagEnvironment `json:"flag_environment,omitempty"`
	// Constraints holds the value of the constraints edge.
	Constraints []*Constraint `json:"constraints,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// FlagEnvironmentOrErr returns the FlagEnvironment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StrategyEdges) FlagEnvironmentOrErr() (*FlagEnvironment, error) {
	if e.FlagEnvironment != nil {
		return e.FlagEnvironment, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: flagenvironment.Label}
	}
	return nil, &NotLoadedError{edge: "flag_environment"}
}

// ConstraintsOrErr returns the Constraints value or an error if the edge
// was not loaded in eager-loading.
func (e StrategyEdges) ConstraintsOrErr() ([]*Constraint, error) {
	if e.loadedTypes[1] {
		return e.Constraints, nil
	}
	return nil, &NotLoadedError{edge: "constraints"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Strategy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case strategy.FieldParameters:
			values[i] = new([]byte)
		case strategy.FieldID, strategy.FieldSortOrder, strategy.FieldFlagEnvironmentID:
			values[i] = new(sql.NullInt64)
		case strategy.FieldName:
			values[i] = new(sql.NullString)
		case strategy.FieldCreatedAt, strategy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Strategy fields.
func (_m *Strategy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case strategy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case strategy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case strategy.FieldParameters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parameters", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Parameters); err != nil {
					return fmt.Errorf("unmarshal field parameters: %w", err)
				}
			}
		case strategy.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case strategy.FieldFlagEnvironmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field flag_environment_id", values[i])
			} else if value.Valid {
				_m.FlagEnvironmentID = int(value.Int64)
			}
		case strategy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case strategy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Strategy.
// This includes values selected through modifiers, order, etc.
func (_m *Strategy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFlagEnvironment queries the "flag_environment" edge of the Strategy entity.
func (_m *Strategy) QueryFlagEnvironment() *FlagEnvironmentQuery {
	return NewStrategyClient(_m.config).QueryFlagEnvironment(_m)
}

// QueryConstraints queries the "constraints" edge of the Strategy entity.
func (_m *Strategy) QueryConstraints() *ConstraintQuery {
	return NewStrategyClient(_m.config).QueryConstraints(_m)
}

// Update returns a builder for updating this Strategy.
// Note that you need to call Strategy.Unwrap() before calling this method if this Strategy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Strategy) Update() *StrategyUpdateOne {
	return NewStrategyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Strategy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Strategy) Unwrap() *Strategy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Strategy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Strategy) String() string {
	var builder strings.Builder
	builder.WriteString("Strategy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("parameters=")
	builder.WriteString(fmt.Sprintf("%v", _m.Parameters))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("flag_environment_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FlagEnvironmentID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Strategies is a parsable slice of Strategy.
type Strategies []*Strategy
