// Code generated by ent, DO NOT EDIT.

package flag

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the flag type in the database.
	Label = "flag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldFlagType holds the string denoting the flag_type field in the database.
	FieldFlagType = "flag_type"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeFlagEnvironments holds the string denoting the flag_environments edge name in mutations.
	EdgeFlagEnvironments = "flag_environments"
	// Table holds the table name of the flag in the database.
	Table = "flags"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "flags"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// FlagEnvironmentsTable is the table that holds the flag_environments relation/edge.
	FlagEnvironmentsTable = "flag_environments"
	// FlagEnvironmentsInverseTable is the table name for the FlagEnvironment entity.
	// It exists in this package in order to avoid circular dependency with the "flagenvironment" package.
	FlagEnvironmentsInverseTable = "flag_environments"
	// FlagEnvironmentsColumn is the table column denoting the flag_environments relation/edge.
	FlagEnvironmentsColumn = "flag_id"
)

// Columns holds all SQL columns for flag fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldFlagType,
	FieldProjectID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// FlagType defines the type for the "flag_type" enum field.
type FlagType string

// FlagType values.
const (
	FlagTypeRelease     FlagType = "release"
	FlagTypeExperiment  FlagType = "experiment"
	FlagTypeOperational FlagType = "operational"
	FlagTypeKillSwitch  FlagType = "kill_switch"
)

func (ft FlagType) String() string {
	return string(ft)
}

// FlagTypeValidator is a validator for the "flag_type" field enum values. It is called by the builders before save.
func FlagTypeValidator(ft FlagType) error {
	switch ft {
	case FlagTypeRelease, FlagTypeExperiment, FlagTypeOperational, FlagTypeKillSwitch:
		return nil
	default:
		return fmt.Errorf("flag: invalid enum value for flag_type field: %q", ft)
	}
}

// OrderOption defines the ordering options for the Flag queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByFlagType orders the results by the flag_type field.
func ByFlagType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlagType, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByFlagEnvironmentsCount orders the results by flag_environments count.
func ByFlagEnvironmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFlagEnvironmentsStep(), opts...)
	}
}

// ByFlagEnvironments orders the results by flag_environments terms.
func ByFlagEnvironments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlagEnvironmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newFlagEnvironmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlagEnvironmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FlagEnvironmentsTable, FlagEnvironmentsColumn),
	)
}
