// Code generated by ent, DO NOT EDIT.

package constraint

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the constraint type in the database.
	Label = "constraint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContextName holds the string denoting the context_name field in the database.
	FieldContextName = "context_name"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldValues holds the string denoting the values field in the database.
	FieldValues = "values"
	// FieldInverted holds the string denoting the inverted field in the database.
	FieldInverted = "inverted"
	// FieldCaseInsensitive holds the string denoting the case_insensitive field in the database.
	FieldCaseInsensitive = "case_insensitive"
	// FieldStrategyID holds the string denoting the strategy_id field in the database.
	FieldStrategyID = "strategy_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeStrategy holds the string denoting the strategy edge name in mutations.
	EdgeStrategy = "strategy"
	// Table holds the table name of the constraint in the database.
	Table = "constraints"
	// StrategyTable is the table that holds the strategy relation/edge.
	StrategyTable = "constraints"
	// StrategyInverseTable is the table name for the Strategy entity.
	// It exists in this package in order to avoid circular dependency with the "strategy" package.
	StrategyInverseTable = "strategies"
	// StrategyColumn is the table column denoting the strategy relation/edge.
	StrategyColumn = "strategy_id"
)

// Columns holds all SQL columns for constraint fields.
var Columns = []string{
	FieldID,
	FieldContextName,
	FieldOperator,
	FieldValues,
	FieldInverted,
	FieldCaseInsensitive,
	FieldStrategyID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInverted holds the default value on creation for the "inverted" field.
	DefaultInverted bool
	// DefaultCaseInsensitive holds the default value on creation for the "case_insensitive" field.
	DefaultCaseInsensitive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Operator defines the type for the "operator" enum field.
type Operator string

// Operator values.
const (
	OperatorIN              Operator = "IN"
	OperatorNOT_IN          Operator = "NOT_IN"
	OperatorSTR_CONTAINS    Operator = "STR_CONTAINS"
	OperatorSTR_STARTS_WITH Operator = "STR_STARTS_WITH"
	OperatorSTR_ENDS_WITH   Operator = "STR_ENDS_WITH"
	OperatorNUM_EQ          Operator = "NUM_EQ"
	OperatorNUM_GT          Operator = "NUM_GT"
	OperatorNUM_GTE         Operator = "NUM_GTE"
	OperatorNUM_LT          Operator = "NUM_LT"
	OperatorNUM_LTE         Operator = "NUM_LTE"
	OperatorDATE_AFTER      Operator = "DATE_AFTER"
	OperatorDATE_BEFORE     Operator = "DATE_BEFORE"
)

func (o Operator) String() string {
	return string(o)
}

// OperatorValidator is a validator for the "operator" field enum values. It is called by the builders before save.
func OperatorValidator(o Operator) error {
	switch o {
	case OperatorIN, OperatorNOT_IN, OperatorSTR_CONTAINS, OperatorSTR_STARTS_WITH, OperatorSTR_ENDS_WITH, OperatorNUM_EQ, OperatorNUM_GT, OperatorNUM_GTE, OperatorNUM_LT, OperatorNUM_LTE, OperatorDATE_AFTER, OperatorDATE_BEFORE:
		return nil
	default:
		return fmt.Errorf("constraint: invalid enum value for operator field: %q", o)
	}
}

// OrderOption defines the ordering options for the Constraint queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByContextName orders the results by the context_name field.
func ByContextName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextName, opts...).ToFunc()
}

// ByOperator orders the results by the operator field.
func ByOperator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperator, opts...).ToFunc()
}

// ByInverted orders the results by the inverted field.
func ByInverted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInverted, opts...).ToFunc()
}

// ByCaseInsensitive orders the results by the case_insensitive field.
func ByCaseInsensitive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaseInsensitive, opts...).ToFunc()
}

// ByStrategyID orders the results by the strategy_id field.
func ByStrategyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStrategyField orders the results by strategy field.
func ByStrategyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStrategyStep(), sql.OrderByField(field, opts...))
	}
}
func newStrategyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StrategyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StrategyTable, StrategyColumn),
	)
}
