// Code generated by ent, DO NOT EDIT.

package constraint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/felipekafuri/bandeira/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Constraint {
	return predicate.Constraint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Constraint {
	return predicate.Constraint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Constraint {
	return predicate.Constraint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Constraint {
	return predicate.Constraint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Constraint {
	return predicate.Constraint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Constraint {
	return predicate.Constraint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Constraint {
	return predicate.Constraint(sql.FieldLTE(FieldID, id))
}

// ContextName applies equality check predicate on the "context_name" field. It's identical to ContextNameEQ.
func ContextName(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldContextName, v))
}

// Inverted applies equality check predicate on the "inverted" field. It's identical to InvertedEQ.
func Inverted(v bool) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldInverted, v))
}

// CaseInsensitive applies equality check predicate on the "case_insensitive" field. It's identical to CaseInsensitiveEQ.
func CaseInsensitive(v bool) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldCaseInsensitive, v))
}

// StrategyID applies equality check predicate on the "strategy_id" field. It's identical to StrategyIDEQ.
func StrategyID(v int) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldStrategyID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldUpdatedAt, v))
}

// ContextNameEQ applies the EQ predicate on the "context_name" field.
func ContextNameEQ(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldContextName, v))
}

// ContextNameNEQ applies the NEQ predicate on the "context_name" field.
func ContextNameNEQ(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldNEQ(FieldContextName, v))
}

// ContextNameIn applies the In predicate on the "context_name" field.
func ContextNameIn(vs ...string) predicate.Constraint {
	return predicate.Constraint(sql.FieldIn(FieldContextName, vs...))
}

// ContextNameNotIn applies the NotIn predicate on the "context_name" field.
func ContextNameNotIn(vs ...string) predicate.Constraint {
	return predicate.Constraint(sql.FieldNotIn(FieldContextName, vs...))
}

// ContextNameGT applies the GT predicate on the "context_name" field.
func ContextNameGT(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldGT(FieldContextName, v))
}

// ContextNameGTE applies the GTE predicate on the "context_name" field.
func ContextNameGTE(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldGTE(FieldContextName, v))
}

// ContextNameLT applies the LT predicate on the "context_name" field.
func ContextNameLT(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldLT(FieldContextName, v))
}

// ContextNameLTE applies the LTE predicate on the "context_name" field.
func ContextNameLTE(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldLTE(FieldContextName, v))
}

// ContextNameContains applies the Contains predicate on the "context_name" field.
func ContextNameContains(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldContains(FieldContextName, v))
}

// ContextNameHasPrefix applies the HasPrefix predicate on the "context_name" field.
func ContextNameHasPrefix(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldHasPrefix(FieldContextName, v))
}

// ContextNameHasSuffix applies the HasSuffix predicate on the "context_name" field.
func ContextNameHasSuffix(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldHasSuffix(FieldContextName, v))
}

// ContextNameEqualFold applies the EqualFold predicate on the "context_name" field.
func ContextNameEqualFold(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldEqualFold(FieldContextName, v))
}

// ContextNameContainsFold applies the ContainsFold predicate on the "context_name" field.
func ContextNameContainsFold(v string) predicate.Constraint {
	return predicate.Constraint(sql.FieldContainsFold(FieldContextName, v))
}

// OperatorEQ applies the EQ predicate on the "operator" field.
func OperatorEQ(v Operator) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldOperator, v))
}

// OperatorNEQ applies the NEQ predicate on the "operator" field.
func OperatorNEQ(v Operator) predicate.Constraint {
	return predicate.Constraint(sql.FieldNEQ(FieldOperator, v))
}

// OperatorIn applies the In predicate on the "operator" field.
func OperatorIn(vs ...Operator) predicate.Constraint {
	return predicate.Constraint(sql.FieldIn(FieldOperator, vs...))
}

// OperatorNotIn applies the NotIn predicate on the "operator" field.
func OperatorNotIn(vs ...Operator) predicate.Constraint {
	return predicate.Constraint(sql.FieldNotIn(FieldOperator, vs...))
}

// InvertedEQ applies the EQ predicate on the "inverted" field.
func InvertedEQ(v bool) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldInverted, v))
}

// InvertedNEQ applies the NEQ predicate on the "inverted" field.
func InvertedNEQ(v bool) predicate.Constraint {
	return predicate.Constraint(sql.FieldNEQ(FieldInverted, v))
}

// CaseInsensitiveEQ applies the EQ predicate on the "case_insensitive" field.
func CaseInsensitiveEQ(v bool) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldCaseInsensitive, v))
}

// CaseInsensitiveNEQ applies the NEQ predicate on the "case_insensitive" field.
func CaseInsensitiveNEQ(v bool) predicate.Constraint {
	return predicate.Constraint(sql.FieldNEQ(FieldCaseInsensitive, v))
}

// StrategyIDEQ applies the EQ predicate on the "strategy_id" field.
func StrategyIDEQ(v int) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldStrategyID, v))
}

// StrategyIDNEQ applies the NEQ predicate on the "strategy_id" field.
func StrategyIDNEQ(v int) predicate.Constraint {
	return predicate.Constraint(sql.FieldNEQ(FieldStrategyID, v))
}

// StrategyIDIn applies the In predicate on the "strategy_id" field.
func StrategyIDIn(vs ...int) predicate.Constraint {
	return predicate.Constraint(sql.FieldIn(FieldStrategyID, vs...))
}

// StrategyIDNotIn applies the NotIn predicate on the "strategy_id" field.
func StrategyIDNotIn(vs ...int) predicate.Constraint {
	return predicate.Constraint(sql.FieldNotIn(FieldStrategyID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Constraint {
	return predicate.Constraint(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasStrategy applies the HasEdge predicate on the "strategy" edge.
func HasStrategy() predicate.Constraint {
	return predicate.Constraint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StrategyTable, StrategyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStrategyWith applies the HasEdge predicate on the "strategy" edge with a given conditions (other predicates).
func HasStrategyWith(preds ...predicate.Strategy) predicate.Constraint {
	return predicate.Constraint(func(s *sql.Selector) {
		step := newStrategyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Constraint) predicate.Constraint {
	return predicate.Constraint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Constraint) predicate.Constraint {
	return predicate.Constraint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Constraint) predicate.Constraint {
	return predicate.Constraint(sql.NotPredicates(p))
}
