// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApiToken is the predicate function for apitoken builders.
type ApiToken func(*sql.Selector)

// Constraint is the predicate function for constraint builders.
type Constraint func(*sql.Selector)

// Environment is the predicate function for environment builders.
type Environment func(*sql.Selector)

// Flag is the predicate function for flag builders.
type Flag func(*sql.Selector)

// FlagEnvironment is the predicate function for flagenvironment builders.
type FlagEnvironment func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Strategy is the predicate function for strategy builders.
type Strategy func(*sql.Selector)
